/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Criar nova proposta de horário
 */
export const propostasHorarioControllerCreateBody = zod.object({
  "idCurso": zod.string(),
  "idPeriodoLetivo": zod.string(),
  "observacoesCoordenador": zod.string().optional()
})

/**
 * @summary Listar todas as propostas
 */
export const propostasHorarioControllerFindAllQueryParams = zod.object({
  "status": zod.enum(['DRAFT', 'PENDENTE_APROVACAO', 'APROVADA', 'REJEITADA']).optional(),
  "idCurso": zod.string().optional(),
  "idPeriodoLetivo": zod.string().optional(),
  "idCoordenador": zod.string().optional()
})

export const propostasHorarioControllerFindAllResponseItem = zod.object({
  "id": zod.string(),
  "status": zod.enum(['DRAFT', 'PENDENTE_APROVACAO', 'APROVADA', 'REJEITADA']),
  "dataSubmissao": zod.object({

}).nullable(),
  "dataAprovacaoRejeicao": zod.object({

}).nullable(),
  "justificativaRejeicao": zod.object({

}).nullable(),
  "observacoesCoordenador": zod.object({

}).nullable(),
  "observacoesDiretor": zod.object({

}).nullable(),
  "dataCriacao": zod.string().datetime({}),
  "dataAtualizacao": zod.string().datetime({}),
  "curso": zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "codigo": zod.object({

}).nullable()
}),
  "periodoLetivo": zod.object({
  "id": zod.string(),
  "ano": zod.number(),
  "semestre": zod.number(),
  "status": zod.string()
}),
  "coordenadorQueSubmeteu": zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "email": zod.string()
}),
  "alocacoesPropostas": zod.array(zod.object({
  "id": zod.string(),
  "diaDaSemana": zod.enum(['SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO']),
  "horaInicio": zod.string(),
  "horaFim": zod.string(),
  "turma": zod.object({
  "id": zod.string(),
  "codigoDaTurma": zod.string(),
  "disciplinaOfertada": zod.object({
  "disciplina": zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "codigo": zod.object({

}).nullable(),
  "cargaHoraria": zod.number()
})
}),
  "professorAlocado": zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "email": zod.string()
}).nullable()
})
}))
})
export const propostasHorarioControllerFindAllResponse = zod.array(propostasHorarioControllerFindAllResponseItem)

/**
 * @summary Buscar proposta DRAFT ativa
 */
export const propostasHorarioControllerFindDraftAtivaQueryParams = zod.object({
  "idCurso": zod.string(),
  "idPeriodoLetivo": zod.string()
})

export const propostasHorarioControllerFindDraftAtivaResponse = zod.object({
  "id": zod.string(),
  "status": zod.enum(['DRAFT', 'PENDENTE_APROVACAO', 'APROVADA', 'REJEITADA']),
  "dataSubmissao": zod.object({

}).nullable(),
  "dataAprovacaoRejeicao": zod.object({

}).nullable(),
  "justificativaRejeicao": zod.object({

}).nullable(),
  "observacoesCoordenador": zod.object({

}).nullable(),
  "observacoesDiretor": zod.object({

}).nullable(),
  "dataCriacao": zod.string().datetime({}),
  "dataAtualizacao": zod.string().datetime({}),
  "curso": zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "codigo": zod.object({

}).nullable()
}),
  "periodoLetivo": zod.object({
  "id": zod.string(),
  "ano": zod.number(),
  "semestre": zod.number(),
  "status": zod.string()
}),
  "coordenadorQueSubmeteu": zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "email": zod.string()
}),
  "alocacoesPropostas": zod.array(zod.object({
  "id": zod.string(),
  "diaDaSemana": zod.enum(['SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO']),
  "horaInicio": zod.string(),
  "horaFim": zod.string(),
  "turma": zod.object({
  "id": zod.string(),
  "codigoDaTurma": zod.string(),
  "disciplinaOfertada": zod.object({
  "disciplina": zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "codigo": zod.object({

}).nullable(),
  "cargaHoraria": zod.number()
})
}),
  "professorAlocado": zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "email": zod.string()
}).nullable()
})
}))
})

/**
 * @summary Listar minhas propostas
 */
export const propostasHorarioControllerFindMinhasPropostasQueryParams = zod.object({
  "status": zod.enum(['DRAFT', 'PENDENTE_APROVACAO', 'APROVADA', 'REJEITADA']).optional(),
  "idCurso": zod.string().optional(),
  "idPeriodoLetivo": zod.string().optional(),
  "idCoordenador": zod.string().optional()
})

export const propostasHorarioControllerFindMinhasPropostasResponseItem = zod.object({
  "id": zod.string(),
  "status": zod.enum(['DRAFT', 'PENDENTE_APROVACAO', 'APROVADA', 'REJEITADA']),
  "dataSubmissao": zod.object({

}).nullable(),
  "dataAprovacaoRejeicao": zod.object({

}).nullable(),
  "justificativaRejeicao": zod.object({

}).nullable(),
  "observacoesCoordenador": zod.object({

}).nullable(),
  "observacoesDiretor": zod.object({

}).nullable(),
  "dataCriacao": zod.string().datetime({}),
  "dataAtualizacao": zod.string().datetime({}),
  "curso": zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "codigo": zod.object({

}).nullable()
}),
  "periodoLetivo": zod.object({
  "id": zod.string(),
  "ano": zod.number(),
  "semestre": zod.number(),
  "status": zod.string()
}),
  "coordenadorQueSubmeteu": zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "email": zod.string()
}),
  "alocacoesPropostas": zod.array(zod.object({
  "id": zod.string(),
  "diaDaSemana": zod.enum(['SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO']),
  "horaInicio": zod.string(),
  "horaFim": zod.string(),
  "turma": zod.object({
  "id": zod.string(),
  "codigoDaTurma": zod.string(),
  "disciplinaOfertada": zod.object({
  "disciplina": zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "codigo": zod.object({

}).nullable(),
  "cargaHoraria": zod.number()
})
}),
  "professorAlocado": zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "email": zod.string()
}).nullable()
})
}))
})
export const propostasHorarioControllerFindMinhasPropostasResponse = zod.array(propostasHorarioControllerFindMinhasPropostasResponseItem)

/**
 * @summary Buscar proposta por ID
 */
export const propostasHorarioControllerFindOneParams = zod.object({
  "id": zod.string()
})

export const propostasHorarioControllerFindOneResponse = zod.object({
  "id": zod.string(),
  "status": zod.enum(['DRAFT', 'PENDENTE_APROVACAO', 'APROVADA', 'REJEITADA']),
  "dataSubmissao": zod.object({

}).nullable(),
  "dataAprovacaoRejeicao": zod.object({

}).nullable(),
  "justificativaRejeicao": zod.object({

}).nullable(),
  "observacoesCoordenador": zod.object({

}).nullable(),
  "observacoesDiretor": zod.object({

}).nullable(),
  "dataCriacao": zod.string().datetime({}),
  "dataAtualizacao": zod.string().datetime({}),
  "curso": zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "codigo": zod.object({

}).nullable()
}),
  "periodoLetivo": zod.object({
  "id": zod.string(),
  "ano": zod.number(),
  "semestre": zod.number(),
  "status": zod.string()
}),
  "coordenadorQueSubmeteu": zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "email": zod.string()
}),
  "alocacoesPropostas": zod.array(zod.object({
  "id": zod.string(),
  "diaDaSemana": zod.enum(['SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO']),
  "horaInicio": zod.string(),
  "horaFim": zod.string(),
  "turma": zod.object({
  "id": zod.string(),
  "codigoDaTurma": zod.string(),
  "disciplinaOfertada": zod.object({
  "disciplina": zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "codigo": zod.object({

}).nullable(),
  "cargaHoraria": zod.number()
})
}),
  "professorAlocado": zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "email": zod.string()
}).nullable()
})
}))
})

/**
 * @summary Enviar proposta para aprovação
 */
export const propostasHorarioControllerEnviarParams = zod.object({
  "id": zod.string()
})

export const propostasHorarioControllerEnviarResponse = zod.object({
  "id": zod.string(),
  "status": zod.enum(['DRAFT', 'PENDENTE_APROVACAO', 'APROVADA', 'REJEITADA']),
  "dataSubmissao": zod.object({

}).nullable(),
  "dataAprovacaoRejeicao": zod.object({

}).nullable(),
  "justificativaRejeicao": zod.object({

}).nullable(),
  "observacoesCoordenador": zod.object({

}).nullable(),
  "observacoesDiretor": zod.object({

}).nullable(),
  "dataCriacao": zod.string().datetime({}),
  "dataAtualizacao": zod.string().datetime({}),
  "curso": zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "codigo": zod.object({

}).nullable()
}),
  "periodoLetivo": zod.object({
  "id": zod.string(),
  "ano": zod.number(),
  "semestre": zod.number(),
  "status": zod.string()
}),
  "coordenadorQueSubmeteu": zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "email": zod.string()
}),
  "alocacoesPropostas": zod.array(zod.object({
  "id": zod.string(),
  "diaDaSemana": zod.enum(['SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO']),
  "horaInicio": zod.string(),
  "horaFim": zod.string(),
  "turma": zod.object({
  "id": zod.string(),
  "codigoDaTurma": zod.string(),
  "disciplinaOfertada": zod.object({
  "disciplina": zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "codigo": zod.object({

}).nullable(),
  "cargaHoraria": zod.number()
})
}),
  "professorAlocado": zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "email": zod.string()
}).nullable()
})
}))
})

/**
 * @summary Aprovar proposta
 */
export const propostasHorarioControllerAprovarParams = zod.object({
  "id": zod.string()
})

export const propostasHorarioControllerAprovarBody = zod.object({
  "observacoesDiretor": zod.string().optional().describe('Observações opcionais do diretor sobre a aprovação')
})

export const propostasHorarioControllerAprovarResponse = zod.object({
  "id": zod.string(),
  "status": zod.enum(['DRAFT', 'PENDENTE_APROVACAO', 'APROVADA', 'REJEITADA']),
  "dataSubmissao": zod.object({

}).nullable(),
  "dataAprovacaoRejeicao": zod.object({

}).nullable(),
  "justificativaRejeicao": zod.object({

}).nullable(),
  "observacoesCoordenador": zod.object({

}).nullable(),
  "observacoesDiretor": zod.object({

}).nullable(),
  "dataCriacao": zod.string().datetime({}),
  "dataAtualizacao": zod.string().datetime({}),
  "curso": zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "codigo": zod.object({

}).nullable()
}),
  "periodoLetivo": zod.object({
  "id": zod.string(),
  "ano": zod.number(),
  "semestre": zod.number(),
  "status": zod.string()
}),
  "coordenadorQueSubmeteu": zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "email": zod.string()
}),
  "alocacoesPropostas": zod.array(zod.object({
  "id": zod.string(),
  "diaDaSemana": zod.enum(['SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO']),
  "horaInicio": zod.string(),
  "horaFim": zod.string(),
  "turma": zod.object({
  "id": zod.string(),
  "codigoDaTurma": zod.string(),
  "disciplinaOfertada": zod.object({
  "disciplina": zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "codigo": zod.object({

}).nullable(),
  "cargaHoraria": zod.number()
})
}),
  "professorAlocado": zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "email": zod.string()
}).nullable()
})
}))
})

/**
 * @summary Rejeitar proposta
 */
export const propostasHorarioControllerRejeitarParams = zod.object({
  "id": zod.string()
})

export const propostasHorarioControllerRejeitarBody = zod.object({
  "justificativaRejeicao": zod.string(),
  "observacoesDiretor": zod.string().optional()
})

export const propostasHorarioControllerRejeitarResponse = zod.object({
  "id": zod.string(),
  "status": zod.enum(['DRAFT', 'PENDENTE_APROVACAO', 'APROVADA', 'REJEITADA']),
  "dataSubmissao": zod.object({

}).nullable(),
  "dataAprovacaoRejeicao": zod.object({

}).nullable(),
  "justificativaRejeicao": zod.object({

}).nullable(),
  "observacoesCoordenador": zod.object({

}).nullable(),
  "observacoesDiretor": zod.object({

}).nullable(),
  "dataCriacao": zod.string().datetime({}),
  "dataAtualizacao": zod.string().datetime({}),
  "curso": zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "codigo": zod.object({

}).nullable()
}),
  "periodoLetivo": zod.object({
  "id": zod.string(),
  "ano": zod.number(),
  "semestre": zod.number(),
  "status": zod.string()
}),
  "coordenadorQueSubmeteu": zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "email": zod.string()
}),
  "alocacoesPropostas": zod.array(zod.object({
  "id": zod.string(),
  "diaDaSemana": zod.enum(['SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO']),
  "horaInicio": zod.string(),
  "horaFim": zod.string(),
  "turma": zod.object({
  "id": zod.string(),
  "codigoDaTurma": zod.string(),
  "disciplinaOfertada": zod.object({
  "disciplina": zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "codigo": zod.object({

}).nullable(),
  "cargaHoraria": zod.number()
})
}),
  "professorAlocado": zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "email": zod.string()
}).nullable()
})
}))
})

