/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Criar uma nova proposta de horário
 */
export const propostasHorarioControllerCreateBody = zod.object({
  "idCurso": zod.string().describe('ID do curso para o qual a proposta será criada'),
  "idPeriodoLetivo": zod.string().describe('ID do período letivo para o qual a proposta será criada'),
  "observacoesCoordenador": zod.string().optional().describe('Observações do coordenador sobre a proposta')
})

/**
 * @summary Listar todas as propostas de horário
 */
export const propostasHorarioControllerFindAllResponseItem = zod.object({
  "id": zod.string().describe('ID único da proposta'),
  "curso": zod.object({
  "id": zod.string().describe('ID do curso'),
  "nome": zod.string().describe('Nome do curso'),
  "codigo": zod.object({

}).optional().describe('Código do curso')
}).describe('Dados do curso'),
  "periodoLetivo": zod.object({
  "id": zod.string().describe('ID do período letivo'),
  "ano": zod.number().describe('Ano do período letivo'),
  "semestre": zod.number().describe('Semestre do período letivo'),
  "dataInicio": zod.string().datetime({}).describe('Data de início do período letivo'),
  "dataFim": zod.string().datetime({}).describe('Data de fim do período letivo')
}).describe('Dados do período letivo'),
  "coordenadorQueSubmeteu": zod.object({
  "id": zod.string().describe('ID do coordenador'),
  "nome": zod.string().describe('Nome do coordenador'),
  "email": zod.string().describe('Email do coordenador')
}).describe('Dados do coordenador que submeteu'),
  "status": zod.enum(['DRAFT', 'PENDENTE_APROVACAO', 'APROVADA', 'REJEITADA']).describe('Status atual da proposta'),
  "dataSubmissao": zod.string().datetime({}).optional().describe('Data de submissão da proposta'),
  "dataAprovacaoRejeicao": zod.string().datetime({}).optional().describe('Data de aprovação ou rejeição'),
  "justificativaRejeicao": zod.object({

}).optional().describe('Justificativa em caso de rejeição'),
  "observacoesCoordenador": zod.object({

}).optional().describe('Observações do coordenador'),
  "observacoesDiretor": zod.object({

}).optional().describe('Observações do diretor'),
  "quantidadeAlocacoes": zod.number().describe('Quantidade de alocações na proposta'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização')
})
export const propostasHorarioControllerFindAllResponse = zod.array(propostasHorarioControllerFindAllResponseItem)

/**
 * @summary Buscar uma proposta de horário pelo ID
 */
export const propostasHorarioControllerFindOneParams = zod.object({
  "id": zod.string().uuid().describe('ID da proposta de horário')
})

export const propostasHorarioControllerFindOneResponse = zod.object({
  "id": zod.string().describe('ID único da proposta'),
  "curso": zod.object({
  "id": zod.string().describe('ID do curso'),
  "nome": zod.string().describe('Nome do curso'),
  "codigo": zod.object({

}).optional().describe('Código do curso')
}).describe('Dados do curso'),
  "periodoLetivo": zod.object({
  "id": zod.string().describe('ID do período letivo'),
  "ano": zod.number().describe('Ano do período letivo'),
  "semestre": zod.number().describe('Semestre do período letivo'),
  "dataInicio": zod.string().datetime({}).describe('Data de início do período letivo'),
  "dataFim": zod.string().datetime({}).describe('Data de fim do período letivo')
}).describe('Dados do período letivo'),
  "coordenadorQueSubmeteu": zod.object({
  "id": zod.string().describe('ID do coordenador'),
  "nome": zod.string().describe('Nome do coordenador'),
  "email": zod.string().describe('Email do coordenador')
}).describe('Dados do coordenador que submeteu'),
  "status": zod.enum(['DRAFT', 'PENDENTE_APROVACAO', 'APROVADA', 'REJEITADA']).describe('Status atual da proposta'),
  "dataSubmissao": zod.string().datetime({}).optional().describe('Data de submissão da proposta'),
  "dataAprovacaoRejeicao": zod.string().datetime({}).optional().describe('Data de aprovação ou rejeição'),
  "justificativaRejeicao": zod.object({

}).optional().describe('Justificativa em caso de rejeição'),
  "observacoesCoordenador": zod.object({

}).optional().describe('Observações do coordenador'),
  "observacoesDiretor": zod.object({

}).optional().describe('Observações do diretor'),
  "quantidadeAlocacoes": zod.number().describe('Quantidade de alocações na proposta'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização')
})

/**
 * @summary Atualizar uma proposta de horário
 */
export const propostasHorarioControllerUpdateParams = zod.object({
  "id": zod.string().uuid().describe('ID da proposta de horário')
})

export const propostasHorarioControllerUpdateBody = zod.object({
  "idCurso": zod.string().optional().describe('ID do curso para o qual a proposta será criada'),
  "idPeriodoLetivo": zod.string().optional().describe('ID do período letivo para o qual a proposta será criada'),
  "observacoesCoordenador": zod.string().optional().describe('Observações do coordenador sobre a proposta')
})

export const propostasHorarioControllerUpdateResponse = zod.object({
  "id": zod.string().describe('ID único da proposta'),
  "curso": zod.object({
  "id": zod.string().describe('ID do curso'),
  "nome": zod.string().describe('Nome do curso'),
  "codigo": zod.object({

}).optional().describe('Código do curso')
}).describe('Dados do curso'),
  "periodoLetivo": zod.object({
  "id": zod.string().describe('ID do período letivo'),
  "ano": zod.number().describe('Ano do período letivo'),
  "semestre": zod.number().describe('Semestre do período letivo'),
  "dataInicio": zod.string().datetime({}).describe('Data de início do período letivo'),
  "dataFim": zod.string().datetime({}).describe('Data de fim do período letivo')
}).describe('Dados do período letivo'),
  "coordenadorQueSubmeteu": zod.object({
  "id": zod.string().describe('ID do coordenador'),
  "nome": zod.string().describe('Nome do coordenador'),
  "email": zod.string().describe('Email do coordenador')
}).describe('Dados do coordenador que submeteu'),
  "status": zod.enum(['DRAFT', 'PENDENTE_APROVACAO', 'APROVADA', 'REJEITADA']).describe('Status atual da proposta'),
  "dataSubmissao": zod.string().datetime({}).optional().describe('Data de submissão da proposta'),
  "dataAprovacaoRejeicao": zod.string().datetime({}).optional().describe('Data de aprovação ou rejeição'),
  "justificativaRejeicao": zod.object({

}).optional().describe('Justificativa em caso de rejeição'),
  "observacoesCoordenador": zod.object({

}).optional().describe('Observações do coordenador'),
  "observacoesDiretor": zod.object({

}).optional().describe('Observações do diretor'),
  "quantidadeAlocacoes": zod.number().describe('Quantidade de alocações na proposta'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização')
})

/**
 * @summary Remover uma proposta de horário
 */
export const propostasHorarioControllerRemoveParams = zod.object({
  "id": zod.string().uuid().describe('ID da proposta de horário')
})

export const propostasHorarioControllerRemoveResponse = zod.object({
  "id": zod.string().describe('ID único da proposta'),
  "curso": zod.object({
  "id": zod.string().describe('ID do curso'),
  "nome": zod.string().describe('Nome do curso'),
  "codigo": zod.object({

}).optional().describe('Código do curso')
}).describe('Dados do curso'),
  "periodoLetivo": zod.object({
  "id": zod.string().describe('ID do período letivo'),
  "ano": zod.number().describe('Ano do período letivo'),
  "semestre": zod.number().describe('Semestre do período letivo'),
  "dataInicio": zod.string().datetime({}).describe('Data de início do período letivo'),
  "dataFim": zod.string().datetime({}).describe('Data de fim do período letivo')
}).describe('Dados do período letivo'),
  "coordenadorQueSubmeteu": zod.object({
  "id": zod.string().describe('ID do coordenador'),
  "nome": zod.string().describe('Nome do coordenador'),
  "email": zod.string().describe('Email do coordenador')
}).describe('Dados do coordenador que submeteu'),
  "status": zod.enum(['DRAFT', 'PENDENTE_APROVACAO', 'APROVADA', 'REJEITADA']).describe('Status atual da proposta'),
  "dataSubmissao": zod.string().datetime({}).optional().describe('Data de submissão da proposta'),
  "dataAprovacaoRejeicao": zod.string().datetime({}).optional().describe('Data de aprovação ou rejeição'),
  "justificativaRejeicao": zod.object({

}).optional().describe('Justificativa em caso de rejeição'),
  "observacoesCoordenador": zod.object({

}).optional().describe('Observações do coordenador'),
  "observacoesDiretor": zod.object({

}).optional().describe('Observações do diretor'),
  "quantidadeAlocacoes": zod.number().describe('Quantidade de alocações na proposta'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização')
})

/**
 * @summary Submeter uma proposta de horário para aprovação
 */
export const propostasHorarioControllerSubmitParams = zod.object({
  "id": zod.string().uuid().describe('ID da proposta de horário')
})

export const propostasHorarioControllerSubmitBody = zod.object({
  "observacoesCoordenador": zod.string().optional().describe('Observações finais do coordenador ao submeter a proposta')
})

export const propostasHorarioControllerSubmitResponse = zod.object({
  "id": zod.string().describe('ID único da proposta'),
  "curso": zod.object({
  "id": zod.string().describe('ID do curso'),
  "nome": zod.string().describe('Nome do curso'),
  "codigo": zod.object({

}).optional().describe('Código do curso')
}).describe('Dados do curso'),
  "periodoLetivo": zod.object({
  "id": zod.string().describe('ID do período letivo'),
  "ano": zod.number().describe('Ano do período letivo'),
  "semestre": zod.number().describe('Semestre do período letivo'),
  "dataInicio": zod.string().datetime({}).describe('Data de início do período letivo'),
  "dataFim": zod.string().datetime({}).describe('Data de fim do período letivo')
}).describe('Dados do período letivo'),
  "coordenadorQueSubmeteu": zod.object({
  "id": zod.string().describe('ID do coordenador'),
  "nome": zod.string().describe('Nome do coordenador'),
  "email": zod.string().describe('Email do coordenador')
}).describe('Dados do coordenador que submeteu'),
  "status": zod.enum(['DRAFT', 'PENDENTE_APROVACAO', 'APROVADA', 'REJEITADA']).describe('Status atual da proposta'),
  "dataSubmissao": zod.string().datetime({}).optional().describe('Data de submissão da proposta'),
  "dataAprovacaoRejeicao": zod.string().datetime({}).optional().describe('Data de aprovação ou rejeição'),
  "justificativaRejeicao": zod.object({

}).optional().describe('Justificativa em caso de rejeição'),
  "observacoesCoordenador": zod.object({

}).optional().describe('Observações do coordenador'),
  "observacoesDiretor": zod.object({

}).optional().describe('Observações do diretor'),
  "quantidadeAlocacoes": zod.number().describe('Quantidade de alocações na proposta'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização')
})

/**
 * @summary Aprovar uma proposta de horário
 */
export const propostasHorarioControllerApproveParams = zod.object({
  "id": zod.string().uuid().describe('ID da proposta de horário')
})

export const propostasHorarioControllerApproveBody = zod.object({
  "observacoesDiretor": zod.string().optional().describe('Observações do diretor ao aprovar a proposta')
})

export const propostasHorarioControllerApproveResponse = zod.object({
  "id": zod.string().describe('ID único da proposta'),
  "curso": zod.object({
  "id": zod.string().describe('ID do curso'),
  "nome": zod.string().describe('Nome do curso'),
  "codigo": zod.object({

}).optional().describe('Código do curso')
}).describe('Dados do curso'),
  "periodoLetivo": zod.object({
  "id": zod.string().describe('ID do período letivo'),
  "ano": zod.number().describe('Ano do período letivo'),
  "semestre": zod.number().describe('Semestre do período letivo'),
  "dataInicio": zod.string().datetime({}).describe('Data de início do período letivo'),
  "dataFim": zod.string().datetime({}).describe('Data de fim do período letivo')
}).describe('Dados do período letivo'),
  "coordenadorQueSubmeteu": zod.object({
  "id": zod.string().describe('ID do coordenador'),
  "nome": zod.string().describe('Nome do coordenador'),
  "email": zod.string().describe('Email do coordenador')
}).describe('Dados do coordenador que submeteu'),
  "status": zod.enum(['DRAFT', 'PENDENTE_APROVACAO', 'APROVADA', 'REJEITADA']).describe('Status atual da proposta'),
  "dataSubmissao": zod.string().datetime({}).optional().describe('Data de submissão da proposta'),
  "dataAprovacaoRejeicao": zod.string().datetime({}).optional().describe('Data de aprovação ou rejeição'),
  "justificativaRejeicao": zod.object({

}).optional().describe('Justificativa em caso de rejeição'),
  "observacoesCoordenador": zod.object({

}).optional().describe('Observações do coordenador'),
  "observacoesDiretor": zod.object({

}).optional().describe('Observações do diretor'),
  "quantidadeAlocacoes": zod.number().describe('Quantidade de alocações na proposta'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização')
})

/**
 * @summary Rejeitar uma proposta de horário
 */
export const propostasHorarioControllerRejectParams = zod.object({
  "id": zod.string().uuid().describe('ID da proposta de horário')
})

export const propostasHorarioControllerRejectBody = zod.object({
  "justificativaRejeicao": zod.string().describe('Justificativa obrigatória para a rejeição da proposta'),
  "observacoesDiretor": zod.string().optional().describe('Observações adicionais do diretor')
})

export const propostasHorarioControllerRejectResponse = zod.object({
  "id": zod.string().describe('ID único da proposta'),
  "curso": zod.object({
  "id": zod.string().describe('ID do curso'),
  "nome": zod.string().describe('Nome do curso'),
  "codigo": zod.object({

}).optional().describe('Código do curso')
}).describe('Dados do curso'),
  "periodoLetivo": zod.object({
  "id": zod.string().describe('ID do período letivo'),
  "ano": zod.number().describe('Ano do período letivo'),
  "semestre": zod.number().describe('Semestre do período letivo'),
  "dataInicio": zod.string().datetime({}).describe('Data de início do período letivo'),
  "dataFim": zod.string().datetime({}).describe('Data de fim do período letivo')
}).describe('Dados do período letivo'),
  "coordenadorQueSubmeteu": zod.object({
  "id": zod.string().describe('ID do coordenador'),
  "nome": zod.string().describe('Nome do coordenador'),
  "email": zod.string().describe('Email do coordenador')
}).describe('Dados do coordenador que submeteu'),
  "status": zod.enum(['DRAFT', 'PENDENTE_APROVACAO', 'APROVADA', 'REJEITADA']).describe('Status atual da proposta'),
  "dataSubmissao": zod.string().datetime({}).optional().describe('Data de submissão da proposta'),
  "dataAprovacaoRejeicao": zod.string().datetime({}).optional().describe('Data de aprovação ou rejeição'),
  "justificativaRejeicao": zod.object({

}).optional().describe('Justificativa em caso de rejeição'),
  "observacoesCoordenador": zod.object({

}).optional().describe('Observações do coordenador'),
  "observacoesDiretor": zod.object({

}).optional().describe('Observações do diretor'),
  "quantidadeAlocacoes": zod.number().describe('Quantidade de alocações na proposta'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização')
})

/**
 * @summary Reabrir uma proposta rejeitada para edição
 */
export const propostasHorarioControllerReopenParams = zod.object({
  "id": zod.string().uuid().describe('ID da proposta de horário')
})

export const propostasHorarioControllerReopenResponse = zod.object({
  "id": zod.string().describe('ID único da proposta'),
  "curso": zod.object({
  "id": zod.string().describe('ID do curso'),
  "nome": zod.string().describe('Nome do curso'),
  "codigo": zod.object({

}).optional().describe('Código do curso')
}).describe('Dados do curso'),
  "periodoLetivo": zod.object({
  "id": zod.string().describe('ID do período letivo'),
  "ano": zod.number().describe('Ano do período letivo'),
  "semestre": zod.number().describe('Semestre do período letivo'),
  "dataInicio": zod.string().datetime({}).describe('Data de início do período letivo'),
  "dataFim": zod.string().datetime({}).describe('Data de fim do período letivo')
}).describe('Dados do período letivo'),
  "coordenadorQueSubmeteu": zod.object({
  "id": zod.string().describe('ID do coordenador'),
  "nome": zod.string().describe('Nome do coordenador'),
  "email": zod.string().describe('Email do coordenador')
}).describe('Dados do coordenador que submeteu'),
  "status": zod.enum(['DRAFT', 'PENDENTE_APROVACAO', 'APROVADA', 'REJEITADA']).describe('Status atual da proposta'),
  "dataSubmissao": zod.string().datetime({}).optional().describe('Data de submissão da proposta'),
  "dataAprovacaoRejeicao": zod.string().datetime({}).optional().describe('Data de aprovação ou rejeição'),
  "justificativaRejeicao": zod.object({

}).optional().describe('Justificativa em caso de rejeição'),
  "observacoesCoordenador": zod.object({

}).optional().describe('Observações do coordenador'),
  "observacoesDiretor": zod.object({

}).optional().describe('Observações do diretor'),
  "quantidadeAlocacoes": zod.number().describe('Quantidade de alocações na proposta'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização')
})

/**
 * @summary Devolver uma proposta aprovada para edição
 */
export const propostasHorarioControllerSendBackParams = zod.object({
  "id": zod.string().uuid().describe('ID da proposta de horário')
})

export const propostasHorarioControllerSendBackBody = zod.object({
  "motivoDevolucao": zod.string().describe('Motivo obrigatório para devolver a proposta para edição')
})

export const propostasHorarioControllerSendBackResponse = zod.object({
  "id": zod.string().describe('ID único da proposta'),
  "curso": zod.object({
  "id": zod.string().describe('ID do curso'),
  "nome": zod.string().describe('Nome do curso'),
  "codigo": zod.object({

}).optional().describe('Código do curso')
}).describe('Dados do curso'),
  "periodoLetivo": zod.object({
  "id": zod.string().describe('ID do período letivo'),
  "ano": zod.number().describe('Ano do período letivo'),
  "semestre": zod.number().describe('Semestre do período letivo'),
  "dataInicio": zod.string().datetime({}).describe('Data de início do período letivo'),
  "dataFim": zod.string().datetime({}).describe('Data de fim do período letivo')
}).describe('Dados do período letivo'),
  "coordenadorQueSubmeteu": zod.object({
  "id": zod.string().describe('ID do coordenador'),
  "nome": zod.string().describe('Nome do coordenador'),
  "email": zod.string().describe('Email do coordenador')
}).describe('Dados do coordenador que submeteu'),
  "status": zod.enum(['DRAFT', 'PENDENTE_APROVACAO', 'APROVADA', 'REJEITADA']).describe('Status atual da proposta'),
  "dataSubmissao": zod.string().datetime({}).optional().describe('Data de submissão da proposta'),
  "dataAprovacaoRejeicao": zod.string().datetime({}).optional().describe('Data de aprovação ou rejeição'),
  "justificativaRejeicao": zod.object({

}).optional().describe('Justificativa em caso de rejeição'),
  "observacoesCoordenador": zod.object({

}).optional().describe('Observações do coordenador'),
  "observacoesDiretor": zod.object({

}).optional().describe('Observações do diretor'),
  "quantidadeAlocacoes": zod.number().describe('Quantidade de alocações na proposta'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização')
})

