/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Obtém a configuração de horário global
 */
export const configuracoesHorarioControllerGetResponse = zod.object({
  "id": zod.string().describe('ID da configuração'),
  "duracaoAulaMinutos": zod.number().describe('Duração da aula em minutos.'),
  "numeroAulasPorTurno": zod.number().describe('Número de aulas por turno.'),
  "inicioTurnoManha": zod.string().describe('Horário de início do turno da manhã (HH:mm).'),
  "fimTurnoManhaCalculado": zod.string().describe('Horário de término do turno da manhã calculado (HH:mm).'),
  "inicioTurnoTarde": zod.string().describe('Horário de início do turno da tarde (HH:mm).'),
  "fimTurnoTardeCalculado": zod.string().describe('Horário de término do turno da tarde calculado (HH:mm).'),
  "inicioTurnoNoite": zod.string().describe('Horário de início do turno da noite (HH:mm).'),
  "fimTurnoNoiteCalculado": zod.string().describe('Horário de término do turno da noite calculado (HH:mm).'),
  "aulasTurnoManha": zod.array(zod.object({
  "inicio": zod.string().describe('Horário de início da aula (HH:mm).'),
  "fim": zod.string().describe('Horário de término da aula (HH:mm).')
})).describe('Lista detalhada dos horários das aulas do turno da manhã.'),
  "aulasTurnoTarde": zod.array(zod.object({
  "inicio": zod.string().describe('Horário de início da aula (HH:mm).'),
  "fim": zod.string().describe('Horário de término da aula (HH:mm).')
})).describe('Lista detalhada dos horários das aulas do turno da tarde.'),
  "aulasTurnoNoite": zod.array(zod.object({
  "inicio": zod.string().describe('Horário de início da aula (HH:mm).'),
  "fim": zod.string().describe('Horário de término da aula (HH:mm).')
})).describe('Lista detalhada dos horários das aulas do turno da noite.'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação da configuração'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização da configuração')
})

/**
 * @summary Cria ou atualiza a configuração de horário global
 */
export const configuracoesHorarioControllerUpsertBody = zod.object({
  "duracaoAulaMinutos": zod.number().optional().describe('Duração da aula em minutos.'),
  "numeroAulasPorTurno": zod.number().optional().describe('Número de aulas por turno.'),
  "inicioTurnoManha": zod.string().optional().describe('Horário de início do turno da manhã (HH:mm).'),
  "inicioTurnoTarde": zod.string().optional().describe('Horário de início do turno da tarde (HH:mm).'),
  "inicioTurnoNoite": zod.string().optional().describe('Horário de início do turno da noite (HH:mm).')
})

export const configuracoesHorarioControllerUpsertResponse = zod.object({
  "id": zod.string().describe('ID da configuração'),
  "duracaoAulaMinutos": zod.number().describe('Duração da aula em minutos.'),
  "numeroAulasPorTurno": zod.number().describe('Número de aulas por turno.'),
  "inicioTurnoManha": zod.string().describe('Horário de início do turno da manhã (HH:mm).'),
  "fimTurnoManhaCalculado": zod.string().describe('Horário de término do turno da manhã calculado (HH:mm).'),
  "inicioTurnoTarde": zod.string().describe('Horário de início do turno da tarde (HH:mm).'),
  "fimTurnoTardeCalculado": zod.string().describe('Horário de término do turno da tarde calculado (HH:mm).'),
  "inicioTurnoNoite": zod.string().describe('Horário de início do turno da noite (HH:mm).'),
  "fimTurnoNoiteCalculado": zod.string().describe('Horário de término do turno da noite calculado (HH:mm).'),
  "aulasTurnoManha": zod.array(zod.object({
  "inicio": zod.string().describe('Horário de início da aula (HH:mm).'),
  "fim": zod.string().describe('Horário de término da aula (HH:mm).')
})).describe('Lista detalhada dos horários das aulas do turno da manhã.'),
  "aulasTurnoTarde": zod.array(zod.object({
  "inicio": zod.string().describe('Horário de início da aula (HH:mm).'),
  "fim": zod.string().describe('Horário de término da aula (HH:mm).')
})).describe('Lista detalhada dos horários das aulas do turno da tarde.'),
  "aulasTurnoNoite": zod.array(zod.object({
  "inicio": zod.string().describe('Horário de início da aula (HH:mm).'),
  "fim": zod.string().describe('Horário de término da aula (HH:mm).')
})).describe('Lista detalhada dos horários das aulas do turno da noite.'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação da configuração'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização da configuração')
})

