/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Criar um novo curso
 */
export const cursosControllerCreateBody = zod.object({
  "nome": zod.string().describe('Nome do curso'),
  "codigo": zod.string().describe('Código do curso (único)'),
  "idCoordenador": zod.string().describe('ID do coordenador principal do curso')
})

/**
 * @summary Listar todos os cursos
 */
export const cursosControllerFindAllResponseNomeMax = 100;
export const cursosControllerFindAllResponseCodigoMax = 20;


export const cursosControllerFindAllResponseItem = zod.object({
  "id": zod.string().describe('ID único do curso no formato UUID v4'),
  "nome": zod.string().max(cursosControllerFindAllResponseNomeMax).describe('Nome completo do curso'),
  "codigo": zod.string().max(cursosControllerFindAllResponseCodigoMax).describe('Código único de identificação do curso'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação do registro no formato ISO 8601'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização no formato ISO 8601'),
  "coordenadorPrincipal": zod.object({
  "id": zod.string().describe('ID único do coordenador no formato UUID v4'),
  "nome": zod.string().describe('Nome completo do coordenador'),
  "email": zod.string().describe('Email do coordenador')
}).optional().describe('Coordenador principal do curso')
})
export const cursosControllerFindAllResponse = zod.array(cursosControllerFindAllResponseItem)

/**
 * @summary Listar cursos do coordenador autenticado
 */
export const cursosControllerFindCursosDoCoordenadorResponseNomeMax = 100;
export const cursosControllerFindCursosDoCoordenadorResponseCodigoMax = 20;


export const cursosControllerFindCursosDoCoordenadorResponseItem = zod.object({
  "id": zod.string().describe('ID único do curso no formato UUID v4'),
  "nome": zod.string().max(cursosControllerFindCursosDoCoordenadorResponseNomeMax).describe('Nome completo do curso'),
  "codigo": zod.string().max(cursosControllerFindCursosDoCoordenadorResponseCodigoMax).describe('Código único de identificação do curso'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação do registro no formato ISO 8601'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização no formato ISO 8601'),
  "coordenadorPrincipal": zod.object({
  "id": zod.string().describe('ID único do coordenador no formato UUID v4'),
  "nome": zod.string().describe('Nome completo do coordenador'),
  "email": zod.string().describe('Email do coordenador')
}).optional().describe('Coordenador principal do curso')
})
export const cursosControllerFindCursosDoCoordenadorResponse = zod.array(cursosControllerFindCursosDoCoordenadorResponseItem)

/**
 * @summary Buscar um curso pelo ID
 */
export const cursosControllerFindOneParams = zod.object({
  "id": zod.string().uuid().describe('ID do curso')
})

export const cursosControllerFindOneResponseNomeMax = 100;
export const cursosControllerFindOneResponseCodigoMax = 20;


export const cursosControllerFindOneResponse = zod.object({
  "id": zod.string().describe('ID único do curso no formato UUID v4'),
  "nome": zod.string().max(cursosControllerFindOneResponseNomeMax).describe('Nome completo do curso'),
  "codigo": zod.string().max(cursosControllerFindOneResponseCodigoMax).describe('Código único de identificação do curso'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação do registro no formato ISO 8601'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização no formato ISO 8601'),
  "coordenadorPrincipal": zod.object({
  "id": zod.string().describe('ID único do coordenador no formato UUID v4'),
  "nome": zod.string().describe('Nome completo do coordenador'),
  "email": zod.string().describe('Email do coordenador')
}).optional().describe('Coordenador principal do curso')
})

/**
 * @summary Atualizar um curso
 */
export const cursosControllerUpdateParams = zod.object({
  "id": zod.string().uuid().describe('ID do curso')
})

export const cursosControllerUpdateBody = zod.object({
  "nome": zod.string().optional().describe('Nome do curso'),
  "codigo": zod.string().optional().describe('Código do curso (único)'),
  "idCoordenador": zod.string().optional().describe('ID do coordenador principal do curso')
})

export const cursosControllerUpdateResponseNomeMax = 100;
export const cursosControllerUpdateResponseCodigoMax = 20;


export const cursosControllerUpdateResponse = zod.object({
  "id": zod.string().describe('ID único do curso no formato UUID v4'),
  "nome": zod.string().max(cursosControllerUpdateResponseNomeMax).describe('Nome completo do curso'),
  "codigo": zod.string().max(cursosControllerUpdateResponseCodigoMax).describe('Código único de identificação do curso'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação do registro no formato ISO 8601'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização no formato ISO 8601'),
  "coordenadorPrincipal": zod.object({
  "id": zod.string().describe('ID único do coordenador no formato UUID v4'),
  "nome": zod.string().describe('Nome completo do coordenador'),
  "email": zod.string().describe('Email do coordenador')
}).optional().describe('Coordenador principal do curso')
})

/**
 * @summary Remover um curso
 */
export const cursosControllerRemoveParams = zod.object({
  "id": zod.string().uuid().describe('ID do curso')
})

export const cursosControllerRemoveResponseNomeMax = 100;
export const cursosControllerRemoveResponseCodigoMax = 20;


export const cursosControllerRemoveResponse = zod.object({
  "id": zod.string().describe('ID único do curso no formato UUID v4'),
  "nome": zod.string().max(cursosControllerRemoveResponseNomeMax).describe('Nome completo do curso'),
  "codigo": zod.string().max(cursosControllerRemoveResponseCodigoMax).describe('Código único de identificação do curso'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação do registro no formato ISO 8601'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização no formato ISO 8601'),
  "coordenadorPrincipal": zod.object({
  "id": zod.string().describe('ID único do coordenador no formato UUID v4'),
  "nome": zod.string().describe('Nome completo do coordenador'),
  "email": zod.string().describe('Email do coordenador')
}).optional().describe('Coordenador principal do curso')
})

