/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Cria um novo usuário
 */
export const usuariosControllerCreateBodySenhaMin = 8;


export const usuariosControllerCreateBody = zod.object({
  "nome": zod.string().describe('Nome completo do usuário'),
  "email": zod.string().describe('Endereço de e-mail do usuário (será usado para login)'),
  "senha": zod.string().min(usuariosControllerCreateBodySenhaMin).describe('Senha do usuário (mínimo de 8 caracteres)'),
  "papel": zod.enum(['ADMIN', 'DIRETOR', 'COORDENADOR', 'PROFESSOR']).describe('Papel do usuário no sistema')
})

/**
 * @summary Lista usuários com filtros e paginação
 */
export const usuariosControllerFindAllQueryParams = zod.object({
  "busca": zod.string().optional().describe('Termo para buscar por nome ou email'),
  "papel": zod.enum(['ADMIN', 'DIRETOR', 'COORDENADOR', 'PROFESSOR']).optional().describe('Filtrar por papel do usuário'),
  "pagina": zod.number().optional().describe('Número da página (padrão: 1)'),
  "limite": zod.number().optional().describe('Número de itens por página (padrão: 10, máximo: 100)')
})

export const usuariosControllerFindAllResponse = zod.object({
  "meta": zod.object({
  "total": zod.number().describe('Número total de itens em todas as páginas'),
  "paginas": zod.number().describe('Número total de páginas disponíveis'),
  "pagina": zod.number().describe('Número da página atual (começando em 1)'),
  "limite": zod.number().describe('Número máximo de itens por página')
}).describe('Metadados de paginação'),
  "data": zod.array(zod.object({
  "id": zod.string().describe('ID único do usuário'),
  "nome": zod.string().describe('Nome completo do usuário'),
  "email": zod.string().describe('Endereço de e-mail do usuário'),
  "papel": zod.enum(['ADMIN', 'DIRETOR', 'COORDENADOR', 'PROFESSOR']).describe('Papel do usuário no sistema'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação do usuário'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização do usuário')
})).describe('Lista de usuários')
})

/**
 * @summary Obtém um usuário pelo ID
 */
export const usuariosControllerFindOneParams = zod.object({
  "id": zod.string().describe('ID do usuário')
})

export const usuariosControllerFindOneResponse = zod.object({
  "id": zod.string().describe('ID único do usuário'),
  "nome": zod.string().describe('Nome completo do usuário'),
  "email": zod.string().describe('Endereço de e-mail do usuário'),
  "papel": zod.enum(['ADMIN', 'DIRETOR', 'COORDENADOR', 'PROFESSOR']).describe('Papel do usuário no sistema'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação do usuário'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização do usuário')
})

/**
 * @summary Atualiza um usuário
 */
export const usuariosControllerUpdateParams = zod.object({
  "id": zod.string().describe('ID do usuário')
})

export const usuariosControllerUpdateBodySenhaMin = 8;


export const usuariosControllerUpdateBody = zod.object({
  "nome": zod.string().optional().describe('Nome completo do usuário'),
  "email": zod.string().optional().describe('Endereço de e-mail do usuário (será usado para login)'),
  "senha": zod.string().min(usuariosControllerUpdateBodySenhaMin).optional().describe('Senha do usuário (mínimo de 8 caracteres)'),
  "papel": zod.enum(['ADMIN', 'DIRETOR', 'COORDENADOR', 'PROFESSOR']).optional().describe('Papel do usuário no sistema')
})

export const usuariosControllerUpdateResponse = zod.object({
  "id": zod.string().describe('ID único do usuário'),
  "nome": zod.string().describe('Nome completo do usuário'),
  "email": zod.string().describe('Endereço de e-mail do usuário'),
  "papel": zod.enum(['ADMIN', 'DIRETOR', 'COORDENADOR', 'PROFESSOR']).describe('Papel do usuário no sistema'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação do usuário'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização do usuário')
})

/**
 * @summary Remove um usuário
 */
export const usuariosControllerRemoveParams = zod.object({
  "id": zod.string().describe('ID do usuário')
})

