/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Cria um novo usuário
 */
export const usuariosControllerCreateBodySenhaMin = 8;


export const usuariosControllerCreateBody = zod.object({
  "nome": zod.string().describe('Nome completo do usuário'),
  "email": zod.string().describe('Endereço de e-mail do usuário (será usado para login)'),
  "senha": zod.string().min(usuariosControllerCreateBodySenhaMin).describe('Senha do usuário (mínimo de 8 caracteres)'),
  "papel": zod.enum(['ADMIN', 'DIRETOR', 'COORDENADOR', 'PROFESSOR']).describe('Papel do usuário no sistema')
})

/**
 * @summary Lista usuários
 */
export const usuariosControllerFindAllQueryParams = zod.object({
  "papel": zod.enum(['ADMIN', 'DIRETOR', 'COORDENADOR', 'PROFESSOR']).optional().describe('Filtrar por papel do usuário')
})

export const usuariosControllerFindAllResponseItem = zod.object({
  "id": zod.string().describe('ID único do usuário'),
  "nome": zod.string().describe('Nome completo do usuário'),
  "email": zod.string().describe('Endereço de e-mail do usuário'),
  "papel": zod.enum(['ADMIN', 'DIRETOR', 'COORDENADOR', 'PROFESSOR']).describe('Papel do usuário no sistema'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação do usuário'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização do usuário')
})
export const usuariosControllerFindAllResponse = zod.array(usuariosControllerFindAllResponseItem)

/**
 * @summary Obtém um usuário pelo ID
 */
export const usuariosControllerFindOneParams = zod.object({
  "id": zod.string().describe('ID do usuário')
})

export const usuariosControllerFindOneResponse = zod.object({
  "id": zod.string().describe('ID único do usuário'),
  "nome": zod.string().describe('Nome completo do usuário'),
  "email": zod.string().describe('Endereço de e-mail do usuário'),
  "papel": zod.enum(['ADMIN', 'DIRETOR', 'COORDENADOR', 'PROFESSOR']).describe('Papel do usuário no sistema'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação do usuário'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização do usuário')
})

/**
 * @summary Atualiza um usuário
 */
export const usuariosControllerUpdateParams = zod.object({
  "id": zod.string().describe('ID do usuário')
})

export const usuariosControllerUpdateBodySenhaMin = 8;


export const usuariosControllerUpdateBody = zod.object({
  "nome": zod.string().optional().describe('Nome completo do usuário'),
  "email": zod.string().optional().describe('Endereço de e-mail do usuário (será usado para login)'),
  "senha": zod.string().min(usuariosControllerUpdateBodySenhaMin).optional().describe('Senha do usuário (mínimo de 8 caracteres)'),
  "papel": zod.enum(['ADMIN', 'DIRETOR', 'COORDENADOR', 'PROFESSOR']).optional().describe('Papel do usuário no sistema')
})

export const usuariosControllerUpdateResponse = zod.object({
  "id": zod.string().describe('ID único do usuário'),
  "nome": zod.string().describe('Nome completo do usuário'),
  "email": zod.string().describe('Endereço de e-mail do usuário'),
  "papel": zod.enum(['ADMIN', 'DIRETOR', 'COORDENADOR', 'PROFESSOR']).describe('Papel do usuário no sistema'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação do usuário'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização do usuário')
})

/**
 * @summary Remove um usuário
 */
export const usuariosControllerRemoveParams = zod.object({
  "id": zod.string().describe('ID do usuário')
})

export const usuariosControllerRemoveResponse = zod.object({
  "id": zod.string().describe('ID único do usuário'),
  "nome": zod.string().describe('Nome completo do usuário'),
  "email": zod.string().describe('Endereço de e-mail do usuário'),
  "papel": zod.enum(['ADMIN', 'DIRETOR', 'COORDENADOR', 'PROFESSOR']).describe('Papel do usuário no sistema'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação do usuário'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização do usuário')
})

