/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


/**
 * Cria uma nova alocação de horário após validar disponibilidade e conflitos
 * @summary Criar nova alocação de horário
 */
export const alocacoesHorariosControllerCreateBody = zod.object({
  "idTurma": zod.string().describe('ID da turma que será alocada'),
  "diaDaSemana": zod.enum(['SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO']).describe('Dia da semana para a alocação'),
  "horaInicio": zod.string().describe('Hora de início da aula (formato HH:mm)'),
  "horaFim": zod.string().describe('Hora de fim da aula (formato HH:mm)')
})

/**
 * Busca alocações aplicando filtros opcionais
 * @summary Buscar alocações com filtros
 */
export const alocacoesHorariosControllerFindManyQueryParams = zod.object({
  "idTurma": zod.string().optional().describe('Filtrar por ID da turma'),
  "idProfessor": zod.string().optional().describe('Filtrar por ID do professor'),
  "idPeriodoLetivo": zod.string().optional().describe('Filtrar por período letivo'),
  "diaDaSemana": zod.enum(['SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO']).optional().describe('Filtrar por dia da semana')
})

export const alocacoesHorariosControllerFindManyResponseItem = zod.object({
  "id": zod.string().describe('ID único da alocação'),
  "idTurma": zod.string().describe('ID da turma alocada'),
  "diaDaSemana": zod.enum(['SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO']).describe('Dia da semana da alocação'),
  "horaInicio": zod.string().describe('Hora de início da aula'),
  "horaFim": zod.string().describe('Hora de fim da aula'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação da alocação'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização'),
  "turma": zod.object({
  "id": zod.string(),
  "codigoDaTurma": zod.string(),
  "disciplinaOfertada": zod.object({

}),
  "professorAlocado": zod.object({

})
}).describe('Dados da turma alocada')
})
export const alocacoesHorariosControllerFindManyResponse = zod.array(alocacoesHorariosControllerFindManyResponseItem)

/**
 * Valida se uma alocação pode ser criada sem conflitos
 * @summary Validar alocação antes de criar
 */
export const alocacoesHorariosControllerValidateBody = zod.object({
  "idTurma": zod.string().describe('ID da turma que será alocada'),
  "diaDaSemana": zod.enum(['SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO']).describe('Dia da semana para a alocação'),
  "horaInicio": zod.string().describe('Hora de início da aula (formato HH:mm)'),
  "horaFim": zod.string().describe('Hora de fim da aula (formato HH:mm)')
})

export const alocacoesHorariosControllerValidateResponse = zod.object({
  "valid": zod.boolean().describe('Indica se a alocação é válida'),
  "error": zod.string().optional().describe('Mensagem de erro caso a alocação seja inválida'),
  "details": zod.object({

}).optional().describe('Detalhes adicionais sobre a validação')
})

/**
 * Busca todas as alocações de uma turma específica
 * @summary Buscar alocações por turma
 */
export const alocacoesHorariosControllerFindByTurmaParams = zod.object({
  "idTurma": zod.string().describe('ID da turma')
})

export const alocacoesHorariosControllerFindByTurmaResponseItem = zod.object({
  "id": zod.string().describe('ID único da alocação'),
  "idTurma": zod.string().describe('ID da turma alocada'),
  "diaDaSemana": zod.enum(['SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO']).describe('Dia da semana da alocação'),
  "horaInicio": zod.string().describe('Hora de início da aula'),
  "horaFim": zod.string().describe('Hora de fim da aula'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação da alocação'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização'),
  "turma": zod.object({
  "id": zod.string(),
  "codigoDaTurma": zod.string(),
  "disciplinaOfertada": zod.object({

}),
  "professorAlocado": zod.object({

})
}).describe('Dados da turma alocada')
})
export const alocacoesHorariosControllerFindByTurmaResponse = zod.array(alocacoesHorariosControllerFindByTurmaResponseItem)

/**
 * Busca todas as alocações de um professor específico
 * @summary Buscar alocações por professor
 */
export const alocacoesHorariosControllerFindByProfessorParams = zod.object({
  "idProfessor": zod.string().describe('ID do professor')
})

export const alocacoesHorariosControllerFindByProfessorResponseItem = zod.object({
  "id": zod.string().describe('ID único da alocação'),
  "idTurma": zod.string().describe('ID da turma alocada'),
  "diaDaSemana": zod.enum(['SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO']).describe('Dia da semana da alocação'),
  "horaInicio": zod.string().describe('Hora de início da aula'),
  "horaFim": zod.string().describe('Hora de fim da aula'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação da alocação'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização'),
  "turma": zod.object({
  "id": zod.string(),
  "codigoDaTurma": zod.string(),
  "disciplinaOfertada": zod.object({

}),
  "professorAlocado": zod.object({

})
}).describe('Dados da turma alocada')
})
export const alocacoesHorariosControllerFindByProfessorResponse = zod.array(alocacoesHorariosControllerFindByProfessorResponseItem)

/**
 * Remove uma alocação de horário existente
 * @summary Remover alocação
 */
export const alocacoesHorariosControllerDeleteParams = zod.object({
  "id": zod.string().describe('ID da alocação')
})

