/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */

export type AlocacoesHorariosControllerFindManyDiaDaSemana = typeof AlocacoesHorariosControllerFindManyDiaDaSemana[keyof typeof AlocacoesHorariosControllerFindManyDiaDaSemana];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AlocacoesHorariosControllerFindManyDiaDaSemana = {
  SEGUNDA: 'SEGUNDA',
  TERCA: 'TERCA',
  QUARTA: 'QUARTA',
  QUINTA: 'QUINTA',
  SEXTA: 'SEXTA',
  SABADO: 'SABADO',
} as const;
