/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import type { AlocacoesHorariosControllerFindManyDiaDaSemana } from './alocacoes-horarios-controller-find-many-dia-da-semana';

export type AlocacoesHorariosControllerFindManyParams = {
/**
 * Filtrar por ID da turma
 */
idTurma?: string;
/**
 * Filtrar por ID do professor
 */
idProfessor?: string;
/**
 * Filtrar por período letivo
 */
idPeriodoLetivo?: string;
/**
 * Filtrar por dia da semana
 */
diaDaSemana?: AlocacoesHorariosControllerFindManyDiaDaSemana;
};
