/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import type { AlocacaoHorarioDtoDiaDaSemana } from "./alocacao-horario-dto-dia-da-semana"
import type { TurmaDto } from "./turma-dto"

export interface AlocacaoHorarioDto {
  /** ID da alocação */
  id: string
  /** Dia da semana */
  diaDaSemana: AlocacaoHorarioDtoDiaDaSemana
  /** Hora de início */
  horaInicio: string
  /** Hora de fim */
  horaFim: string
  /** Turma */
  turma: TurmaDto
  /** Data de criação */
  dataCriacao: string
  /** Data de atualização */
  dataAtualizacao: string
}
