/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import type { AlocacaoHorarioDtoDiaDaSemana } from "./alocacao-horario-dto-dia-da-semana"
import type { TurmaDto } from "./turma-dto"

export interface AlocacaoHorarioDto {
  id: string
  diaDaSemana: AlocacaoHorarioDtoDiaDaSemana
  horaInicio: string
  horaFim: string
  turma: TurmaDto
}
