/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */

export interface AulaHorarioDto {
  /** Horário de início da aula (HH:mm). */
  inicio: string;
  /** Horário de término da aula (HH:mm). */
  fim: string;
}
