/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */

/**
 * Novo status do período letivo
 */
export type ChangeStatusPeriodoLetivoDtoStatus = typeof ChangeStatusPeriodoLetivoDtoStatus[keyof typeof ChangeStatusPeriodoLetivoDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChangeStatusPeriodoLetivoDtoStatus = {
  ATIVO: 'ATIVO',
  INATIVO: 'INATIVO',
} as const;
