/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */

export interface CoordenadorDto {
  /** ID do usuário coordenador */
  id: string;
  /** Nome do coordenador */
  nome: string;
  /** Email do coordenador */
  email: string;
}
