/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */

export interface CoordenadorSimplificadoDto {
  /** ID único do coordenador no formato UUID v4 */
  id: string
  /** Nome completo do coordenador */
  nome: string
  /** Email do coordenador */
  email: string
}
