/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */

export interface CreateDisciplinaOfertadaSimplificadaDto {
  /** ID da disciplina a ser ofertada */
  idDisciplina: string
  /**
   * Quantidade de turmas para esta disciplina
   * @minimum 1
   */
  quantidadeTurmas: number
}
