/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import type { CreateAlocacaoHorarioDtoDiaDaSemana } from './create-alocacao-horario-dto-dia-da-semana';

export interface CreateAlocacaoHorarioDto {
  /** ID da turma que será alocada */
  idTurma: string;
  /** Dia da semana para a alocação */
  diaDaSemana: CreateAlocacaoHorarioDtoDiaDaSemana;
  /** Hora de início da aula (formato HH:mm) */
  horaInicio: string;
  /** Hora de fim da aula (formato HH:mm) */
  horaFim: string;
}
