/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */

export interface CreatePropostaHorarioDto {
  /** ID do curso para o qual a proposta será criada */
  idCurso: string
  /** ID do período letivo para o qual a proposta será criada */
  idPeriodoLetivo: string
  /** Observações do coordenador sobre a proposta */
  observacoesCoordenador?: string
}
