/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import type { CursoSimplificadoDtoCodigo } from "./curso-simplificado-dto-codigo"

export interface CursoSimplificadoDto {
  /** ID do curso */
  id: string
  /** Nome do curso */
  nome: string
  /** Código do curso */
  codigo: CursoSimplificadoDtoCodigo
}
