/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import type { DisciplinaDtoCodigo } from "./disciplina-dto-codigo"

export interface DisciplinaDto {
  id: string
  nome: string
  /** @nullable */
  codigo: DisciplinaDtoCodigo
  cargaHoraria: number
}
