/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import type { DisciplinaBasicaDto } from './disciplina-basica-dto';

export interface DisciplinaOfertadaBasicaDto {
  /** ID da disciplina ofertada */
  id: string;
  /** Dados da disciplina */
  disciplina: DisciplinaBasicaDto;
}
