/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */

export type DisciplinasControllerFindAllParams = {
  /**
   * Filtrar disciplinas por nome (pesquisa parcial)
   */
  nome?: string
  /**
   * Filtrar disciplinas por código (pesquisa parcial)
   */
  codigo?: string
}
