/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */

export interface DisciplinaBasicaDto {
  /** ID da disciplina */
  id: string
  /** Nome da disciplina */
  nome: string
  /** Código da disciplina */
  codigo: string
  /** Carga horária da disciplina */
  cargaHoraria: number
}
