/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */

export interface DisciplinaResponseDto {
  /** ID único da disciplina */
  id: string;
  /** Nome da disciplina */
  nome: string;
  /** Código único da disciplina */
  codigo?: string;
  /** Carga horária total da disciplina em horas */
  cargaHoraria: number;
  /** Data de criação do registro */
  dataCriacao: string;
  /** Data da última atualização do registro */
  dataAtualizacao: string;
}
