/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import type { DisponibilidadeProfessorControllerGetSlotsValidos200SlotsItem } from './disponibilidade-professor-controller-get-slots-validos200-slots-item';

export type DisponibilidadeProfessorControllerGetSlotsValidos200 = {
  slots?: DisponibilidadeProfessorControllerGetSlotsValidos200SlotsItem[];
};
