/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */

export interface PaginationMeta {
  /** Número total de itens em todas as páginas */
  total: number;
  /** Número total de páginas disponíveis */
  paginas: number;
  /** Número da página atual (começando em 1) */
  pagina: number;
  /** Número máximo de itens por página */
  limite: number;
}
