/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */

export interface PeriodoLetivoDto {
  /** ID do período letivo (UUID) */
  id: string;
  /** Ano do período letivo */
  ano: number;
  /** Semestre do período letivo */
  semestre: number;
  /**
   * Data de início do período letivo
   * @nullable
   */
  dataInicio: string | null;
  /**
   * Data de fim do período letivo
   * @nullable
   */
  dataFim: string | null;
  /** Data de criação do período letivo */
  createdAt: string;
  /** Data da última atualização do período letivo */
  updatedAt: string;
}
