/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import type { PeriodoLetivoResponseDtoStatus } from './periodo-letivo-response-dto-status';

export interface PeriodoLetivoResponseDto {
  /** ID único do período letivo */
  id: string;
  /** Ano do período letivo */
  ano: number;
  /** Semestre do período letivo (1 ou 2) */
  semestre: number;
  /** Status atual do período letivo */
  status: PeriodoLetivoResponseDtoStatus;
  /** Data de início do período letivo */
  dataInicio: string;
  /** Data de fim do período letivo */
  dataFim: string;
  /** Data de criação do registro */
  dataCriacao: string;
  /** Data da última atualização do registro */
  dataAtualizacao: string;
}
