/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */

export interface PeriodoLetivoPropostaDto {
  /** ID do período letivo */
  id: string
  /** Ano do período letivo */
  ano: number
  /** Semestre do período letivo */
  semestre: number
  /** Data de início do período letivo */
  dataInicio: string
  /** Data de fim do período letivo */
  dataFim: string
}
