/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */

export interface ProfessorBasicoDto {
  /** ID do professor */
  id: string
  /** Nome do professor */
  nome: string
  /** Email do professor */
  email: string
}
