/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import type { PropostaHorarioResponseDtoCurso } from "./proposta-horario-response-dto-curso"
import type { PropostaHorarioResponseDtoPeriodoLetivo } from "./proposta-horario-response-dto-periodo-letivo"
import type { PropostaHorarioResponseDtoCoordenadorQueSubmeteu } from "./proposta-horario-response-dto-coordenador-que-submeteu"
import type { PropostaHorarioResponseDtoStatus } from "./proposta-horario-response-dto-status"
import type { PropostaHorarioResponseDtoDataSubmissao } from "./proposta-horario-response-dto-data-submissao"
import type { PropostaHorarioResponseDtoDataAprovacaoRejeicao } from "./proposta-horario-response-dto-data-aprovacao-rejeicao"
import type { PropostaHorarioResponseDtoJustificativaRejeicao } from "./proposta-horario-response-dto-justificativa-rejeicao"
import type { PropostaHorarioResponseDtoObservacoesCoordenador } from "./proposta-horario-response-dto-observacoes-coordenador"
import type { PropostaHorarioResponseDtoObservacoesDiretor } from "./proposta-horario-response-dto-observacoes-diretor"

export interface PropostaHorarioResponseDto {
  /** ID único da proposta */
  id: string
  /** Dados do curso */
  curso: PropostaHorarioResponseDtoCurso
  /** Dados do período letivo */
  periodoLetivo: PropostaHorarioResponseDtoPeriodoLetivo
  /** Dados do coordenador que submeteu */
  coordenadorQueSubmeteu: PropostaHorarioResponseDtoCoordenadorQueSubmeteu
  /** Status atual da proposta */
  status: PropostaHorarioResponseDtoStatus
  /** Data de submissão da proposta */
  dataSubmissao?: PropostaHorarioResponseDtoDataSubmissao
  /** Data de aprovação ou rejeição */
  dataAprovacaoRejeicao?: PropostaHorarioResponseDtoDataAprovacaoRejeicao
  /** Justificativa em caso de rejeição */
  justificativaRejeicao?: PropostaHorarioResponseDtoJustificativaRejeicao
  /** Observações do coordenador */
  observacoesCoordenador?: PropostaHorarioResponseDtoObservacoesCoordenador
  /** Observações do diretor */
  observacoesDiretor?: PropostaHorarioResponseDtoObservacoesDiretor
  /** Quantidade de alocações na proposta */
  quantidadeAlocacoes: number
  /** Data de criação */
  dataCriacao: string
  /** Data da última atualização */
  dataAtualizacao: string
}
