/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import type { PropostasHorarioControllerFindAllStatus } from "./propostas-horario-controller-find-all-status"

export type PropostasHorarioControllerFindAllParams = {
  /**
   * Filtrar por status
   */
  status?: PropostasHorarioControllerFindAllStatus
  /**
   * Filtrar por curso
   */
  idCurso?: string
  /**
   * Filtrar por período letivo
   */
  idPeriodoLetivo?: string
  /**
   * Filtrar por coordenador
   */
  idCoordenador?: string
}
