/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */

export type PropostasHorarioControllerCalcularCompletude200 = {
  /** Total de aulas necessárias */
  totalAulasNecessarias?: number
  /** Número de aulas já alocadas */
  aulasAlocadas?: number
  /** Percentual de completude */
  percentualCompleto?: number
  /** Disciplinas que ainda não têm alocações */
  disciplinasSemAlocacao?: string[]
}
