/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import type { PropostasHorarioControllerFindMinhasPropostasStatus } from "./propostas-horario-controller-find-minhas-propostas-status"

export type PropostasHorarioControllerFindMinhasPropostasParams = {
  /**
   * Filtrar por status
   */
  status?: PropostasHorarioControllerFindMinhasPropostasStatus
  /**
   * Filtrar por curso
   */
  idCurso?: string
  /**
   * Filtrar por período letivo
   */
  idPeriodoLetivo?: string
  /**
   * Filtrar por ID do coordenador
   */
  idCoordenador?: string
}
