/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */

export type PropostasHorarioControllerFindDraftAtivaParams = {
  /**
   * ID do curso
   */
  idCurso: string
  /**
   * ID do período letivo
   */
  idPeriodoLetivo: string
}
