/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import type { PropostaHorarioResponseDtoStatus } from "./proposta-horario-response-dto-status"
import type { PropostaHorarioResponseDtoDataSubmissao } from "./proposta-horario-response-dto-data-submissao"
import type { PropostaHorarioResponseDtoDataAprovacaoRejeicao } from "./proposta-horario-response-dto-data-aprovacao-rejeicao"
import type { PropostaHorarioResponseDtoJustificativaRejeicao } from "./proposta-horario-response-dto-justificativa-rejeicao"
import type { PropostaHorarioResponseDtoObservacoesCoordenador } from "./proposta-horario-response-dto-observacoes-coordenador"
import type { PropostaHorarioResponseDtoObservacoesDiretor } from "./proposta-horario-response-dto-observacoes-diretor"
import type { CursoSimplificadoDto } from "./curso-simplificado-dto"
import type { PeriodoLetivoSimplificadoDto } from "./periodo-letivo-simplificado-dto"
import type { CoordenadorSimplificadoDto } from "./coordenador-simplificado-dto"
import type { AlocacaoHorarioDto } from "./alocacao-horario-dto"

export interface PropostaHorarioResponseDto {
  /** ID da proposta */
  id: string
  /** Status da proposta */
  status: PropostaHorarioResponseDtoStatus
  /**
   * Data de submissão
   * @nullable
   */
  dataSubmissao: PropostaHorarioResponseDtoDataSubmissao
  /**
   * Data de aprovação ou rejeição
   * @nullable
   */
  dataAprovacaoRejeicao: PropostaHorarioResponseDtoDataAprovacaoRejeicao
  /**
   * Justificativa de rejeição
   * @nullable
   */
  justificativaRejeicao: PropostaHorarioResponseDtoJustificativaRejeicao
  /**
   * Observações do coordenador
   * @nullable
   */
  observacoesCoordenador: PropostaHorarioResponseDtoObservacoesCoordenador
  /**
   * Observações do diretor
   * @nullable
   */
  observacoesDiretor: PropostaHorarioResponseDtoObservacoesDiretor
  /** Data de criação */
  dataCriacao: string
  /** Data de atualização */
  dataAtualizacao: string
  /** Curso */
  curso: CursoSimplificadoDto
  /** Período letivo */
  periodoLetivo: PeriodoLetivoSimplificadoDto
  /** Coordenador que submeteu */
  coordenadorQueSubmeteu: CoordenadorSimplificadoDto
  /** Alocações propostas */
  alocacoesPropostas: AlocacaoHorarioDto[]
}
