/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import type { CursoPropostaDto } from "./curso-proposta-dto"
import type { PeriodoLetivoPropostaDto } from "./periodo-letivo-proposta-dto"
import type { CoordenadorPropostaDto } from "./coordenador-proposta-dto"
import type { PropostaHorarioResponseDtoStatus } from "./proposta-horario-response-dto-status"
import type { PropostaHorarioResponseDtoJustificativaRejeicao } from "./proposta-horario-response-dto-justificativa-rejeicao"
import type { PropostaHorarioResponseDtoObservacoesCoordenador } from "./proposta-horario-response-dto-observacoes-coordenador"
import type { PropostaHorarioResponseDtoObservacoesDiretor } from "./proposta-horario-response-dto-observacoes-diretor"

export interface PropostaHorarioResponseDto {
  /** ID único da proposta */
  id: string
  /** Dados do curso */
  curso: CursoPropostaDto
  /** Dados do período letivo */
  periodoLetivo: PeriodoLetivoPropostaDto
  /** Dados do coordenador que submeteu */
  coordenadorQueSubmeteu: CoordenadorPropostaDto
  /** Status atual da proposta */
  status: PropostaHorarioResponseDtoStatus
  /** Data de submissão da proposta */
  dataSubmissao?: string
  /** Data de aprovação ou rejeição */
  dataAprovacaoRejeicao?: string
  /** Justificativa em caso de rejeição */
  justificativaRejeicao?: PropostaHorarioResponseDtoJustificativaRejeicao
  /** Observações do coordenador */
  observacoesCoordenador?: PropostaHorarioResponseDtoObservacoesCoordenador
  /** Observações do diretor */
  observacoesDiretor?: PropostaHorarioResponseDtoObservacoesDiretor
  /** Quantidade de alocações na proposta */
  quantidadeAlocacoes: number
  /** Data de criação */
  dataCriacao: string
  /** Data da última atualização */
  dataAtualizacao: string
}
