/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */

/**
 * Observações do diretor
 * @nullable
 */
export type PropostaHorarioResponseDtoObservacoesDiretor = {
  [key: string]: unknown
} | null
