/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */

export interface SignInDto {
  /** Endereço de e-mail do usuário para login */
  email: string;
  /** Senha do usuário (mínimo de 8 caracteres) */
  senha: string;
}
