/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import type { DisciplinaOfertadaDto } from "./disciplina-ofertada-dto"
import type { TurmaDtoProfessorAlocado } from "./turma-dto-professor-alocado"

export interface TurmaDto {
  /** ID da turma */
  id: string
  /** Código da turma */
  codigoDaTurma: string
  /** Disciplina ofertada */
  disciplinaOfertada: DisciplinaOfertadaDto
  /**
   * Professor alocado
   * @nullable
   */
  professorAlocado: TurmaDtoProfessorAlocado
}
