/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import type { TurmaBasicaDtoDisciplinaOfertada } from './turma-basica-dto-disciplina-ofertada';
import type { TurmaBasicaDtoProfessorAlocado } from './turma-basica-dto-professor-alocado';

export interface TurmaBasicaDto {
  id: string;
  codigoDaTurma: string;
  disciplinaOfertada: TurmaBasicaDtoDisciplinaOfertada;
  professorAlocado: TurmaBasicaDtoProfessorAlocado;
}
