/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */

export interface UpdateDisciplinaOfertadaDto {
  /** ID da disciplina que será ofertada (UUID) */
  idDisciplina?: string
  /** ID do período letivo em que a disciplina será ofertada (UUID) */
  idPeriodoLetivo?: string
  /**
   * Quantidade de turmas para esta disciplina ofertada
   * @minimum 1
   */
  quantidadeTurmas?: number
}
