/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */

/**
 * Status da disponibilidade
 */
export type UpdateDisponibilidadeDtoStatus = typeof UpdateDisponibilidadeDtoStatus[keyof typeof UpdateDisponibilidadeDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateDisponibilidadeDtoStatus = {
  DISPONIVEL: 'DISPONIVEL',
  INDISPONIVEL: 'INDISPONIVEL',
} as const;
