/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */

/**
 * Status inicial do período letivo
 */
export type UpdatePeriodoLetivoDtoStatus = typeof UpdatePeriodoLetivoDtoStatus[keyof typeof UpdatePeriodoLetivoDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdatePeriodoLetivoDtoStatus = {
  ATIVO: 'ATIVO',
  INATIVO: 'INATIVO',
} as const;
