/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */

export interface UpdateMatrizCurricularDto {
  /** Nome da matriz curricular */
  nome?: string
  /** ID do curso ao qual a matriz curricular pertence */
  idCurso?: string
  /** Lista de IDs das disciplinas da matriz curricular */
  disciplinasIds?: string[]
  /** Lista de IDs das disciplinas a serem adicionadas à matriz curricular */
  disciplinasParaAdicionar?: string[]
  /** Lista de IDs das disciplinas a serem removidas da matriz curricular */
  disciplinasParaRemover?: string[]
}
