/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */

export interface UpsertConfiguracaoHorarioDto {
  /** Duração da aula em minutos. */
  duracaoAulaMinutos?: number;
  /** Número de aulas por turno. */
  numeroAulasPorTurno?: number;
  /** Horário de início do turno da manhã (HH:mm). */
  inicioTurnoManha?: string;
  /** Horário de início do turno da tarde (HH:mm). */
  inicioTurnoTarde?: string;
  /** Horário de início do turno da noite (HH:mm). */
  inicioTurnoNoite?: string;
}
