/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import type { UsuarioResponseDtoPapel } from "./usuario-response-dto-papel"

export interface UsuarioResponseDto {
  /** ID único do usuário */
  id: string
  /** Nome completo do usuário */
  nome: string
  /** Endereço de e-mail do usuário */
  email: string
  /** Papel do usuário no sistema */
  papel: UsuarioResponseDtoPapel
  /** Data de criação do usuário */
  dataCriacao: string
  /** Data da última atualização do usuário */
  dataAtualizacao: string
}
