/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import type { ValidateAlocacaoDtoDiaDaSemana } from "./validate-alocacao-dto-dia-da-semana"

export interface ValidateAlocacaoDto {
  /** ID da turma que será alocada */
  idTurma: string
  /** Dia da semana para a alocação */
  diaDaSemana: ValidateAlocacaoDtoDiaDaSemana
  /** Hora de início da aula (formato HH:mm) */
  horaInicio: string
  /** Hora de fim da aula (formato HH:mm) */
  horaFim: string
}
