/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import type { ValidateAlocacaoResponseDtoDetails } from "./validate-alocacao-response-dto-details"

export interface ValidateAlocacaoResponseDto {
  /** Indica se a alocação é válida */
  valid: boolean
  /** Mensagem de erro caso a alocação seja inválida */
  error?: string
  /** Detalhes adicionais sobre a validação */
  details?: ValidateAlocacaoResponseDtoDetails
}
