/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Criar uma nova disciplina
 */
export const disciplinasControllerCreateBody = zod.object({
  "nome": zod.string().describe('Nome da disciplina'),
  "codigo": zod.string().optional().describe('Código único da disciplina'),
  "cargaHoraria": zod.number().describe('Carga horária total da disciplina em horas')
})

/**
 * @summary Listar todas as disciplinas
 */
export const disciplinasControllerFindAllQueryParams = zod.object({
  "nome": zod.string().optional().describe('Filtrar disciplinas por nome (pesquisa parcial)'),
  "codigo": zod.string().optional().describe('Filtrar disciplinas por código (pesquisa parcial)')
})

export const disciplinasControllerFindAllResponseItem = zod.object({
  "id": zod.string().describe('ID único da disciplina'),
  "nome": zod.string().describe('Nome da disciplina'),
  "codigo": zod.string().optional().describe('Código único da disciplina'),
  "cargaHoraria": zod.number().describe('Carga horária total da disciplina em horas'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação do registro'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização do registro')
})
export const disciplinasControllerFindAllResponse = zod.array(disciplinasControllerFindAllResponseItem)

/**
 * @summary Buscar disciplina por ID
 */
export const disciplinasControllerFindOneParams = zod.object({
  "id": zod.string().describe('ID da disciplina a ser buscada')
})

export const disciplinasControllerFindOneResponse = zod.object({
  "id": zod.string().describe('ID único da disciplina'),
  "nome": zod.string().describe('Nome da disciplina'),
  "codigo": zod.string().optional().describe('Código único da disciplina'),
  "cargaHoraria": zod.number().describe('Carga horária total da disciplina em horas'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação do registro'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização do registro')
})

/**
 * @summary Atualizar disciplina por ID
 */
export const disciplinasControllerUpdateParams = zod.object({
  "id": zod.string().describe('ID da disciplina a ser atualizada')
})

export const disciplinasControllerUpdateBody = zod.object({
  "nome": zod.string().optional().describe('Nome da disciplina'),
  "codigo": zod.string().optional().describe('Código único da disciplina'),
  "cargaHoraria": zod.number().optional().describe('Carga horária total da disciplina em horas')
})

export const disciplinasControllerUpdateResponse = zod.object({
  "id": zod.string().describe('ID único da disciplina'),
  "nome": zod.string().describe('Nome da disciplina'),
  "codigo": zod.string().optional().describe('Código único da disciplina'),
  "cargaHoraria": zod.number().describe('Carga horária total da disciplina em horas'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação do registro'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização do registro')
})

/**
 * @summary Remover disciplina por ID
 */
export const disciplinasControllerRemoveParams = zod.object({
  "id": zod.string().describe('ID da disciplina a ser removida')
})

