/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Criar nova matriz curricular
 */
export const matrizesCurricularesControllerCreateBody = zod.object({
  "nome": zod.string().describe('Nome da matriz curricular'),
  "disciplinasIds": zod.array(zod.string()).describe('Lista de IDs das disciplinas da matriz curricular')
})

/**
 * @summary Listar todas as matrizes curriculares
 */
export const matrizesCurricularesControllerFindAllQueryParams = zod.object({
  "idCurso": zod.string().optional().describe('ID do curso para filtrar matrizes curriculares')
})

export const matrizesCurricularesControllerFindAllResponseItem = zod.object({
  "id": zod.string().describe('ID único da matriz curricular'),
  "nome": zod.string().describe('Nome da matriz curricular'),
  "idCurso": zod.string().describe('ID do curso ao qual a matriz curricular pertence'),
  "nomeCurso": zod.string().describe('Nome do curso ao qual a matriz curricular pertence'),
  "createdAt": zod.string().datetime({}).describe('Data de criação da matriz curricular'),
  "updatedAt": zod.string().datetime({}).describe('Data da última atualização da matriz curricular'),
  "disciplinas": zod.array(zod.object({
  "id": zod.string().describe('ID único da disciplina'),
  "nome": zod.string().describe('Nome da disciplina'),
  "codigo": zod.string().optional().describe('Código único da disciplina'),
  "cargaHoraria": zod.number().describe('Carga horária total da disciplina em horas'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação do registro'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização do registro')
})).describe('Lista de disciplinas da matriz curricular')
})
export const matrizesCurricularesControllerFindAllResponse = zod.array(matrizesCurricularesControllerFindAllResponseItem)

/**
 * @summary Buscar matriz curricular por ID
 */
export const matrizesCurricularesControllerFindOneParams = zod.object({
  "id": zod.string().describe('ID da matriz curricular')
})

export const matrizesCurricularesControllerFindOneResponse = zod.object({
  "id": zod.string().describe('ID único da matriz curricular'),
  "nome": zod.string().describe('Nome da matriz curricular'),
  "idCurso": zod.string().describe('ID do curso ao qual a matriz curricular pertence'),
  "nomeCurso": zod.string().describe('Nome do curso ao qual a matriz curricular pertence'),
  "createdAt": zod.string().datetime({}).describe('Data de criação da matriz curricular'),
  "updatedAt": zod.string().datetime({}).describe('Data da última atualização da matriz curricular'),
  "disciplinas": zod.array(zod.object({
  "id": zod.string().describe('ID único da disciplina'),
  "nome": zod.string().describe('Nome da disciplina'),
  "codigo": zod.string().optional().describe('Código único da disciplina'),
  "cargaHoraria": zod.number().describe('Carga horária total da disciplina em horas'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação do registro'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização do registro')
})).describe('Lista de disciplinas da matriz curricular')
})

/**
 * @summary Atualizar matriz curricular
 */
export const matrizesCurricularesControllerUpdateParams = zod.object({
  "id": zod.string().describe('ID da matriz curricular')
})

export const matrizesCurricularesControllerUpdateBody = zod.object({
  "nome": zod.string().optional().describe('Nome da matriz curricular'),
  "disciplinasIds": zod.array(zod.string()).optional().describe('Lista de IDs das disciplinas da matriz curricular'),
  "disciplinasParaAdicionar": zod.array(zod.string()).optional().describe('Lista de IDs das disciplinas a serem adicionadas à matriz curricular'),
  "disciplinasParaRemover": zod.array(zod.string()).optional().describe('Lista de IDs das disciplinas a serem removidas da matriz curricular')
})

export const matrizesCurricularesControllerUpdateResponse = zod.object({
  "id": zod.string().describe('ID único da matriz curricular'),
  "nome": zod.string().describe('Nome da matriz curricular'),
  "idCurso": zod.string().describe('ID do curso ao qual a matriz curricular pertence'),
  "nomeCurso": zod.string().describe('Nome do curso ao qual a matriz curricular pertence'),
  "createdAt": zod.string().datetime({}).describe('Data de criação da matriz curricular'),
  "updatedAt": zod.string().datetime({}).describe('Data da última atualização da matriz curricular'),
  "disciplinas": zod.array(zod.object({
  "id": zod.string().describe('ID único da disciplina'),
  "nome": zod.string().describe('Nome da disciplina'),
  "codigo": zod.string().optional().describe('Código único da disciplina'),
  "cargaHoraria": zod.number().describe('Carga horária total da disciplina em horas'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação do registro'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização do registro')
})).describe('Lista de disciplinas da matriz curricular')
})

/**
 * @summary Remover matriz curricular
 */
export const matrizesCurricularesControllerRemoveParams = zod.object({
  "id": zod.string().describe('ID da matriz curricular')
})

