/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


/**
 * Cria uma nova disponibilidade para um professor. Apenas o próprio professor, admin ou diretor podem criar.
 * @summary Criar nova disponibilidade
 */
export const disponibilidadeProfessorControllerCreateBodyHoraInicioRegExp = new RegExp('^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$');
export const disponibilidadeProfessorControllerCreateBodyHoraFimRegExp = new RegExp('^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$');
export const disponibilidadeProfessorControllerCreateBodyStatusDefault = "DISPONIVEL";

export const disponibilidadeProfessorControllerCreateBody = zod.object({
  "idUsuarioProfessor": zod.string().describe('ID do usuário professor'),
  "idPeriodoLetivo": zod.string().describe('ID do período letivo'),
  "diaDaSemana": zod.enum(['SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO']).describe('Dia da semana'),
  "horaInicio": zod.string().regex(disponibilidadeProfessorControllerCreateBodyHoraInicioRegExp).describe('Horário de início (formato HH:mm)'),
  "horaFim": zod.string().regex(disponibilidadeProfessorControllerCreateBodyHoraFimRegExp).describe('Horário de fim (formato HH:mm)'),
  "status": zod.enum(['DISPONIVEL', 'INDISPONIVEL']).describe('Status da disponibilidade')
})

/**
 * Lista disponibilidades com filtros opcionais e paginação. Professores veem apenas suas próprias.
 * @summary Listar disponibilidades
 */
export const disponibilidadeProfessorControllerFindAllQueryLimitMax = 100;


export const disponibilidadeProfessorControllerFindAllQueryParams = zod.object({
  "professorId": zod.string().optional().describe('Filtrar por ID do professor'),
  "periodoLetivoId": zod.string().optional().describe('Filtrar por ID do período letivo'),
  "diaSemana": zod.enum(['SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO']).optional().describe('Filtrar por dia da semana'),
  "status": zod.enum(['DISPONIVEL', 'INDISPONIVEL']).optional().describe('Filtrar por status'),
  "orderBy": zod.enum(['diaDaSemana', 'horaInicio', 'horaFim', 'dataCriacao']).optional().describe('Campo para ordenação'),
  "orderDirection": zod.enum(['asc', 'desc']).optional().describe('Direção da ordenação'),
  "page": zod.number().min(1).optional().describe('Página (padrão: 1)'),
  "limit": zod.number().min(1).max(disponibilidadeProfessorControllerFindAllQueryLimitMax).optional().describe('Itens por página (padrão: 10)')
})

export const disponibilidadeProfessorControllerFindAllResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.string().describe('ID único da disponibilidade'),
  "diaDaSemana": zod.enum(['SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO']).describe('Dia da semana'),
  "horaInicio": zod.string().describe('Horário de início (formato HH:mm)'),
  "horaFim": zod.string().describe('Horário de fim (formato HH:mm)'),
  "status": zod.enum(['DISPONIVEL', 'INDISPONIVEL']).describe('Status da disponibilidade'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização'),
  "usuarioProfessor": zod.object({
  "id": zod.string().describe('ID do professor'),
  "nome": zod.string().describe('Nome do professor'),
  "email": zod.string().describe('Email do professor')
}).describe('Dados do professor'),
  "periodoLetivo": zod.object({
  "id": zod.string().describe('ID do período letivo'),
  "ano": zod.number().describe('Ano do período'),
  "semestre": zod.number().describe('Semestre do período'),
  "status": zod.string().describe('Status do período letivo')
}).describe('Dados do período letivo')
})).optional(),
  "total": zod.number().optional(),
  "page": zod.number().optional(),
  "limit": zod.number().optional(),
  "totalPages": zod.number().optional()
})

/**
 * Busca uma disponibilidade específica pelo ID
 * @summary Buscar disponibilidade por ID
 */
export const disponibilidadeProfessorControllerFindOneParams = zod.object({
  "id": zod.string().describe('ID da disponibilidade')
})

export const disponibilidadeProfessorControllerFindOneResponse = zod.object({
  "id": zod.string().describe('ID único da disponibilidade'),
  "diaDaSemana": zod.enum(['SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO']).describe('Dia da semana'),
  "horaInicio": zod.string().describe('Horário de início (formato HH:mm)'),
  "horaFim": zod.string().describe('Horário de fim (formato HH:mm)'),
  "status": zod.enum(['DISPONIVEL', 'INDISPONIVEL']).describe('Status da disponibilidade'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização'),
  "usuarioProfessor": zod.object({
  "id": zod.string().describe('ID do professor'),
  "nome": zod.string().describe('Nome do professor'),
  "email": zod.string().describe('Email do professor')
}).describe('Dados do professor'),
  "periodoLetivo": zod.object({
  "id": zod.string().describe('ID do período letivo'),
  "ano": zod.number().describe('Ano do período'),
  "semestre": zod.number().describe('Semestre do período'),
  "status": zod.string().describe('Status do período letivo')
}).describe('Dados do período letivo')
})

/**
 * Atualiza uma disponibilidade existente. Apenas o próprio professor, admin ou diretor podem atualizar.
 * @summary Atualizar disponibilidade
 */
export const disponibilidadeProfessorControllerUpdateParams = zod.object({
  "id": zod.string().describe('ID da disponibilidade')
})

export const disponibilidadeProfessorControllerUpdateBodyHoraInicioRegExp = new RegExp('^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$');
export const disponibilidadeProfessorControllerUpdateBodyHoraFimRegExp = new RegExp('^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$');
export const disponibilidadeProfessorControllerUpdateBodyStatusDefault = "DISPONIVEL";

export const disponibilidadeProfessorControllerUpdateBody = zod.object({
  "diaDaSemana": zod.enum(['SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO']).optional().describe('Dia da semana'),
  "horaInicio": zod.string().regex(disponibilidadeProfessorControllerUpdateBodyHoraInicioRegExp).optional().describe('Horário de início (formato HH:mm)'),
  "horaFim": zod.string().regex(disponibilidadeProfessorControllerUpdateBodyHoraFimRegExp).optional().describe('Horário de fim (formato HH:mm)'),
  "status": zod.enum(['DISPONIVEL', 'INDISPONIVEL']).default(disponibilidadeProfessorControllerUpdateBodyStatusDefault).describe('Status da disponibilidade')
})

export const disponibilidadeProfessorControllerUpdateResponse = zod.object({
  "id": zod.string().describe('ID único da disponibilidade'),
  "diaDaSemana": zod.enum(['SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO']).describe('Dia da semana'),
  "horaInicio": zod.string().describe('Horário de início (formato HH:mm)'),
  "horaFim": zod.string().describe('Horário de fim (formato HH:mm)'),
  "status": zod.enum(['DISPONIVEL', 'INDISPONIVEL']).describe('Status da disponibilidade'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização'),
  "usuarioProfessor": zod.object({
  "id": zod.string().describe('ID do professor'),
  "nome": zod.string().describe('Nome do professor'),
  "email": zod.string().describe('Email do professor')
}).describe('Dados do professor'),
  "periodoLetivo": zod.object({
  "id": zod.string().describe('ID do período letivo'),
  "ano": zod.number().describe('Ano do período'),
  "semestre": zod.number().describe('Semestre do período'),
  "status": zod.string().describe('Status do período letivo')
}).describe('Dados do período letivo')
})

/**
 * Remove uma disponibilidade existente. Apenas o próprio professor, admin ou diretor podem remover.
 * @summary Remover disponibilidade
 */
export const disponibilidadeProfessorControllerRemoveParams = zod.object({
  "id": zod.string().describe('ID da disponibilidade')
})

/**
 * Lista todas as disponibilidades de um professor específico
 * @summary Listar disponibilidades por professor
 */
export const disponibilidadeProfessorControllerFindByProfessorParams = zod.object({
  "professorId": zod.string().describe('ID do professor')
})

export const disponibilidadeProfessorControllerFindByProfessorQueryLimitMax = 100;


export const disponibilidadeProfessorControllerFindByProfessorQueryParams = zod.object({
  "periodoLetivoId": zod.string().optional().describe('ID do período letivo para filtrar'),
  "diaSemana": zod.enum(['SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO']).optional().describe('Dia da semana para filtrar'),
  "status": zod.enum(['DISPONIVEL', 'INDISPONIVEL']).optional().describe('Status da disponibilidade para filtrar'),
  "orderBy": zod.enum(['diaDaSemana', 'horaInicio', 'horaFim', 'dataCriacao']).optional().describe('Campo para ordenação'),
  "orderDirection": zod.enum(['asc', 'desc']).optional().describe('Direção da ordenação'),
  "page": zod.number().min(1).optional().describe('Página para paginação (começa em 1)'),
  "limit": zod.number().min(1).max(disponibilidadeProfessorControllerFindByProfessorQueryLimitMax).optional().describe('Quantidade de itens por página')
})

/**
 * Lista todas as disponibilidades de um período letivo específico
 * @summary Listar disponibilidades por período
 */
export const disponibilidadeProfessorControllerFindByPeriodoParams = zod.object({
  "periodoId": zod.string().describe('ID do período letivo')
})

export const disponibilidadeProfessorControllerFindByPeriodoQueryLimitMax = 100;


export const disponibilidadeProfessorControllerFindByPeriodoQueryParams = zod.object({
  "professorId": zod.string().optional().describe('ID do professor para filtrar'),
  "periodoLetivoId": zod.string().optional().describe('ID do período letivo para filtrar'),
  "diaSemana": zod.enum(['SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO']).optional().describe('Dia da semana para filtrar'),
  "status": zod.enum(['DISPONIVEL', 'INDISPONIVEL']).optional().describe('Status da disponibilidade para filtrar'),
  "orderBy": zod.enum(['diaDaSemana', 'horaInicio', 'horaFim', 'dataCriacao']).optional().describe('Campo para ordenação'),
  "orderDirection": zod.enum(['asc', 'desc']).optional().describe('Direção da ordenação'),
  "page": zod.number().min(1).optional().describe('Página para paginação (começa em 1)'),
  "limit": zod.number().min(1).max(disponibilidadeProfessorControllerFindByPeriodoQueryLimitMax).optional().describe('Quantidade de itens por página')
})

/**
 * Lista disponibilidades de um professor em um período letivo específico
 * @summary Listar disponibilidades por professor e período
 */
export const disponibilidadeProfessorControllerFindByProfessorAndPeriodoParams = zod.object({
  "professorId": zod.string().describe('ID do professor'),
  "periodoId": zod.string().describe('ID do período letivo')
})

export const disponibilidadeProfessorControllerFindByProfessorAndPeriodoResponseItem = zod.object({
  "id": zod.string().describe('ID único da disponibilidade'),
  "diaDaSemana": zod.enum(['SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO']).describe('Dia da semana'),
  "horaInicio": zod.string().describe('Horário de início (formato HH:mm)'),
  "horaFim": zod.string().describe('Horário de fim (formato HH:mm)'),
  "status": zod.enum(['DISPONIVEL', 'INDISPONIVEL']).describe('Status da disponibilidade'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização'),
  "usuarioProfessor": zod.object({
  "id": zod.string().describe('ID do professor'),
  "nome": zod.string().describe('Nome do professor'),
  "email": zod.string().describe('Email do professor')
}).describe('Dados do professor'),
  "periodoLetivo": zod.object({
  "id": zod.string().describe('ID do período letivo'),
  "ano": zod.number().describe('Ano do período'),
  "semestre": zod.number().describe('Semestre do período'),
  "status": zod.string().describe('Status do período letivo')
}).describe('Dados do período letivo')
})
export const disponibilidadeProfessorControllerFindByProfessorAndPeriodoResponse = zod.array(disponibilidadeProfessorControllerFindByProfessorAndPeriodoResponseItem)

