/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AlocacaoHorarioResponseDto,
  AlocacoesHorariosControllerFindManyParams,
  CreateAlocacaoHorarioDto,
  ValidateAlocacaoDto,
  ValidateAlocacaoResponseDto
} from '../../model';

import { orvalCustomInstance } from '../../../lib/orval-axios-instance';
import type { ErrorType , BodyType } from '../../../lib/orval-axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Cria uma nova alocação de horário após validar disponibilidade e conflitos
 * @summary Criar nova alocação de horário
 */
export const alocacoesHorariosControllerCreate = (
    createAlocacaoHorarioDto: BodyType<CreateAlocacaoHorarioDto>,
 options?: SecondParameter<typeof orvalCustomInstance>,signal?: AbortSignal
) => {
      
      
      return orvalCustomInstance<AlocacaoHorarioResponseDto>(
      {url: `/alocacoes-horarios`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createAlocacaoHorarioDto, signal
    },
      options);
    }
  


export const getAlocacoesHorariosControllerCreateMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof alocacoesHorariosControllerCreate>>, TError,{data: BodyType<CreateAlocacaoHorarioDto>}, TContext>, request?: SecondParameter<typeof orvalCustomInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof alocacoesHorariosControllerCreate>>, TError,{data: BodyType<CreateAlocacaoHorarioDto>}, TContext> => {

const mutationKey = ['alocacoesHorariosControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof alocacoesHorariosControllerCreate>>, {data: BodyType<CreateAlocacaoHorarioDto>}> = (props) => {
          const {data} = props ?? {};

          return  alocacoesHorariosControllerCreate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AlocacoesHorariosControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof alocacoesHorariosControllerCreate>>>
    export type AlocacoesHorariosControllerCreateMutationBody = BodyType<CreateAlocacaoHorarioDto>
    export type AlocacoesHorariosControllerCreateMutationError = ErrorType<void>

    /**
 * @summary Criar nova alocação de horário
 */
export const useAlocacoesHorariosControllerCreate = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof alocacoesHorariosControllerCreate>>, TError,{data: BodyType<CreateAlocacaoHorarioDto>}, TContext>, request?: SecondParameter<typeof orvalCustomInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof alocacoesHorariosControllerCreate>>,
        TError,
        {data: BodyType<CreateAlocacaoHorarioDto>},
        TContext
      > => {

      const mutationOptions = getAlocacoesHorariosControllerCreateMutationOptions(options);

      return useMutation(mutationOptions );
    }
    /**
 * Busca alocações aplicando filtros opcionais
 * @summary Buscar alocações com filtros
 */
export const alocacoesHorariosControllerFindMany = (
    params?: AlocacoesHorariosControllerFindManyParams,
 options?: SecondParameter<typeof orvalCustomInstance>,signal?: AbortSignal
) => {
      
      
      return orvalCustomInstance<AlocacaoHorarioResponseDto[]>(
      {url: `/alocacoes-horarios`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getAlocacoesHorariosControllerFindManyQueryKey = (params?: AlocacoesHorariosControllerFindManyParams,) => {
    return ['alocacoes-horarios', ...(params ? [params]: [])] as const;
    }

    
export const getAlocacoesHorariosControllerFindManyQueryOptions = <TData = Awaited<ReturnType<typeof alocacoesHorariosControllerFindMany>>, TError = ErrorType<unknown>>(params?: AlocacoesHorariosControllerFindManyParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof alocacoesHorariosControllerFindMany>>, TError, TData>, request?: SecondParameter<typeof orvalCustomInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAlocacoesHorariosControllerFindManyQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof alocacoesHorariosControllerFindMany>>> = ({ signal }) => alocacoesHorariosControllerFindMany(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof alocacoesHorariosControllerFindMany>>, TError, TData> & { queryKey: QueryKey }
}

export type AlocacoesHorariosControllerFindManyQueryResult = NonNullable<Awaited<ReturnType<typeof alocacoesHorariosControllerFindMany>>>
export type AlocacoesHorariosControllerFindManyQueryError = ErrorType<unknown>


/**
 * @summary Buscar alocações com filtros
 */

export function useAlocacoesHorariosControllerFindMany<TData = Awaited<ReturnType<typeof alocacoesHorariosControllerFindMany>>, TError = ErrorType<unknown>>(
 params?: AlocacoesHorariosControllerFindManyParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof alocacoesHorariosControllerFindMany>>, TError, TData>, request?: SecondParameter<typeof orvalCustomInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getAlocacoesHorariosControllerFindManyQueryOptions(params,options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Valida se uma alocação pode ser criada sem conflitos
 * @summary Validar alocação antes de criar
 */
export const alocacoesHorariosControllerValidate = (
    validateAlocacaoDto: BodyType<ValidateAlocacaoDto>,
 options?: SecondParameter<typeof orvalCustomInstance>,signal?: AbortSignal
) => {
      
      
      return orvalCustomInstance<ValidateAlocacaoResponseDto>(
      {url: `/alocacoes-horarios/validate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: validateAlocacaoDto, signal
    },
      options);
    }
  


export const getAlocacoesHorariosControllerValidateMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof alocacoesHorariosControllerValidate>>, TError,{data: BodyType<ValidateAlocacaoDto>}, TContext>, request?: SecondParameter<typeof orvalCustomInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof alocacoesHorariosControllerValidate>>, TError,{data: BodyType<ValidateAlocacaoDto>}, TContext> => {

const mutationKey = ['alocacoesHorariosControllerValidate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof alocacoesHorariosControllerValidate>>, {data: BodyType<ValidateAlocacaoDto>}> = (props) => {
          const {data} = props ?? {};

          return  alocacoesHorariosControllerValidate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AlocacoesHorariosControllerValidateMutationResult = NonNullable<Awaited<ReturnType<typeof alocacoesHorariosControllerValidate>>>
    export type AlocacoesHorariosControllerValidateMutationBody = BodyType<ValidateAlocacaoDto>
    export type AlocacoesHorariosControllerValidateMutationError = ErrorType<unknown>

    /**
 * @summary Validar alocação antes de criar
 */
export const useAlocacoesHorariosControllerValidate = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof alocacoesHorariosControllerValidate>>, TError,{data: BodyType<ValidateAlocacaoDto>}, TContext>, request?: SecondParameter<typeof orvalCustomInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof alocacoesHorariosControllerValidate>>,
        TError,
        {data: BodyType<ValidateAlocacaoDto>},
        TContext
      > => {

      const mutationOptions = getAlocacoesHorariosControllerValidateMutationOptions(options);

      return useMutation(mutationOptions );
    }
    /**
 * Busca todas as alocações de uma turma específica
 * @summary Buscar alocações por turma
 */
export const alocacoesHorariosControllerFindByTurma = (
    idTurma: string,
 options?: SecondParameter<typeof orvalCustomInstance>,signal?: AbortSignal
) => {
      
      
      return orvalCustomInstance<AlocacaoHorarioResponseDto[]>(
      {url: `/alocacoes-horarios/turma/${idTurma}`, method: 'GET', signal
    },
      options);
    }
  

export const getAlocacoesHorariosControllerFindByTurmaQueryKey = (idTurma: string,) => {
    return ['alocacoes-horarios','turma',idTurma] as const;
    }

    
export const getAlocacoesHorariosControllerFindByTurmaQueryOptions = <TData = Awaited<ReturnType<typeof alocacoesHorariosControllerFindByTurma>>, TError = ErrorType<unknown>>(idTurma: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof alocacoesHorariosControllerFindByTurma>>, TError, TData>, request?: SecondParameter<typeof orvalCustomInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAlocacoesHorariosControllerFindByTurmaQueryKey(idTurma);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof alocacoesHorariosControllerFindByTurma>>> = ({ signal }) => alocacoesHorariosControllerFindByTurma(idTurma, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(idTurma), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof alocacoesHorariosControllerFindByTurma>>, TError, TData> & { queryKey: QueryKey }
}

export type AlocacoesHorariosControllerFindByTurmaQueryResult = NonNullable<Awaited<ReturnType<typeof alocacoesHorariosControllerFindByTurma>>>
export type AlocacoesHorariosControllerFindByTurmaQueryError = ErrorType<unknown>


/**
 * @summary Buscar alocações por turma
 */

export function useAlocacoesHorariosControllerFindByTurma<TData = Awaited<ReturnType<typeof alocacoesHorariosControllerFindByTurma>>, TError = ErrorType<unknown>>(
 idTurma: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof alocacoesHorariosControllerFindByTurma>>, TError, TData>, request?: SecondParameter<typeof orvalCustomInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getAlocacoesHorariosControllerFindByTurmaQueryOptions(idTurma,options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Busca todas as alocações de um professor específico
 * @summary Buscar alocações por professor
 */
export const alocacoesHorariosControllerFindByProfessor = (
    idProfessor: string,
 options?: SecondParameter<typeof orvalCustomInstance>,signal?: AbortSignal
) => {
      
      
      return orvalCustomInstance<AlocacaoHorarioResponseDto[]>(
      {url: `/alocacoes-horarios/professor/${idProfessor}`, method: 'GET', signal
    },
      options);
    }
  

export const getAlocacoesHorariosControllerFindByProfessorQueryKey = (idProfessor: string,) => {
    return ['alocacoes-horarios','professor',idProfessor] as const;
    }

    
export const getAlocacoesHorariosControllerFindByProfessorQueryOptions = <TData = Awaited<ReturnType<typeof alocacoesHorariosControllerFindByProfessor>>, TError = ErrorType<unknown>>(idProfessor: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof alocacoesHorariosControllerFindByProfessor>>, TError, TData>, request?: SecondParameter<typeof orvalCustomInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAlocacoesHorariosControllerFindByProfessorQueryKey(idProfessor);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof alocacoesHorariosControllerFindByProfessor>>> = ({ signal }) => alocacoesHorariosControllerFindByProfessor(idProfessor, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(idProfessor), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof alocacoesHorariosControllerFindByProfessor>>, TError, TData> & { queryKey: QueryKey }
}

export type AlocacoesHorariosControllerFindByProfessorQueryResult = NonNullable<Awaited<ReturnType<typeof alocacoesHorariosControllerFindByProfessor>>>
export type AlocacoesHorariosControllerFindByProfessorQueryError = ErrorType<unknown>


/**
 * @summary Buscar alocações por professor
 */

export function useAlocacoesHorariosControllerFindByProfessor<TData = Awaited<ReturnType<typeof alocacoesHorariosControllerFindByProfessor>>, TError = ErrorType<unknown>>(
 idProfessor: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof alocacoesHorariosControllerFindByProfessor>>, TError, TData>, request?: SecondParameter<typeof orvalCustomInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getAlocacoesHorariosControllerFindByProfessorQueryOptions(idProfessor,options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Remove uma alocação de horário existente
 * @summary Remover alocação
 */
export const alocacoesHorariosControllerDelete = (
    id: string,
 options?: SecondParameter<typeof orvalCustomInstance>,) => {
      
      
      return orvalCustomInstance<void>(
      {url: `/alocacoes-horarios/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getAlocacoesHorariosControllerDeleteMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof alocacoesHorariosControllerDelete>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof orvalCustomInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof alocacoesHorariosControllerDelete>>, TError,{id: string}, TContext> => {

const mutationKey = ['alocacoesHorariosControllerDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof alocacoesHorariosControllerDelete>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  alocacoesHorariosControllerDelete(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AlocacoesHorariosControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof alocacoesHorariosControllerDelete>>>
    
    export type AlocacoesHorariosControllerDeleteMutationError = ErrorType<void>

    /**
 * @summary Remover alocação
 */
export const useAlocacoesHorariosControllerDelete = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof alocacoesHorariosControllerDelete>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof orvalCustomInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof alocacoesHorariosControllerDelete>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getAlocacoesHorariosControllerDeleteMutationOptions(options);

      return useMutation(mutationOptions );
    }
    