/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Obter detalhes de uma turma específica
 */
export const turmasControllerFindOneParams = zod.object({
  "id": zod.string().describe('ID da turma (UUID)')
})

export const turmasControllerFindOneResponse = zod.object({
  "id": zod.string().describe('ID da turma'),
  "codigoDaTurma": zod.string().describe('Código/identificador da turma'),
  "idDisciplinaOfertada": zod.string().describe('ID da disciplina ofertada à qual esta turma pertence.'),
  "disciplinaOfertada": zod.object({
  "idDisciplina": zod.string().describe('ID da disciplina que será ofertada (UUID)'),
  "idPeriodoLetivo": zod.string().describe('ID do período letivo em que a disciplina será ofertada (UUID)'),
  "quantidadeTurmas": zod.number().min(1).describe('Quantidade de turmas para esta disciplina ofertada'),
  "id": zod.string().describe('ID da oferta da disciplina (UUID)'),
  "disciplina": zod.object({
  "id": zod.string().describe('ID único da disciplina'),
  "nome": zod.string().describe('Nome da disciplina'),
  "codigo": zod.string().optional().describe('Código único da disciplina'),
  "cargaHoraria": zod.number().describe('Carga horária total da disciplina em horas'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação do registro'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização do registro')
}).describe('Detalhes da disciplina ofertada'),
  "periodoLetivo": zod.object({
  "id": zod.string().describe('ID único do período letivo'),
  "ano": zod.number().describe('Ano do período letivo'),
  "semestre": zod.number().describe('Semestre do período letivo (1 ou 2)'),
  "status": zod.enum(['ATIVO', 'INATIVO']).describe('Status atual do período letivo'),
  "dataInicio": zod.string().describe('Data de início do período letivo'),
  "dataFim": zod.string().describe('Data de fim do período letivo'),
  "dataCriacao": zod.string().describe('Data de criação do registro'),
  "dataAtualizacao": zod.string().describe('Data da última atualização do registro')
}).describe('Detalhes do período letivo da oferta'),
  "createdAt": zod.string().datetime({}).describe('Data de criação da oferta da disciplina'),
  "updatedAt": zod.string().datetime({}).describe('Data da última atualização da oferta da disciplina')
}).optional().describe('Detalhes da disciplina ofertada'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação da turma'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização da turma')
})

