/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query"
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query"

import type {
  AprovarPropostaDto,
  CreatePropostaHorarioDto,
  PropostaHorarioResponseDto,
  PropostasHorarioControllerFindAllParams,
  PropostasHorarioControllerFindDraftAtivaParams,
  PropostasHorarioControllerFindMinhasPropostasParams,
  RejeitarPropostaDto,
} from "../../model"

import { orvalCustomInstance } from "../../../lib/orval-axios-instance"
import type { ErrorType, BodyType } from "../../../lib/orval-axios-instance"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Cria uma nova proposta de horário em estado DRAFT para o coordenador autenticado
 * @summary Criar nova proposta de horário
 */
export const propostasHorarioControllerCreate = (
  createPropostaHorarioDto: BodyType<CreatePropostaHorarioDto>,
  options?: SecondParameter<typeof orvalCustomInstance>,
  signal?: AbortSignal,
) => {
  return orvalCustomInstance<PropostaHorarioResponseDto>(
    {
      url: `/propostas-horario`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createPropostaHorarioDto,
      signal,
    },
    options,
  )
}

export const getPropostasHorarioControllerCreateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof propostasHorarioControllerCreate>>,
    TError,
    { data: BodyType<CreatePropostaHorarioDto> },
    TContext
  >
  request?: SecondParameter<typeof orvalCustomInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof propostasHorarioControllerCreate>>,
  TError,
  { data: BodyType<CreatePropostaHorarioDto> },
  TContext
> => {
  const mutationKey = ["propostasHorarioControllerCreate"]
  const { mutation: mutationOptions, request: requestOptions } =
    options ?
      (
        options.mutation &&
        "mutationKey" in options.mutation &&
        options.mutation.mutationKey
      ) ?
        options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof propostasHorarioControllerCreate>>,
    { data: BodyType<CreatePropostaHorarioDto> }
  > = (props) => {
    const { data } = props ?? {}

    return propostasHorarioControllerCreate(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PropostasHorarioControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof propostasHorarioControllerCreate>>
>
export type PropostasHorarioControllerCreateMutationBody =
  BodyType<CreatePropostaHorarioDto>
export type PropostasHorarioControllerCreateMutationError = ErrorType<void>

/**
 * @summary Criar nova proposta de horário
 */
export const usePropostasHorarioControllerCreate = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof propostasHorarioControllerCreate>>,
      TError,
      { data: BodyType<CreatePropostaHorarioDto> },
      TContext
    >
    request?: SecondParameter<typeof orvalCustomInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof propostasHorarioControllerCreate>>,
  TError,
  { data: BodyType<CreatePropostaHorarioDto> },
  TContext
> => {
  const mutationOptions =
    getPropostasHorarioControllerCreateMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Lista todas as propostas de horário (disponível apenas para diretores e admins)
 * @summary Listar todas as propostas
 */
export const propostasHorarioControllerFindAll = (
  params?: PropostasHorarioControllerFindAllParams,
  options?: SecondParameter<typeof orvalCustomInstance>,
  signal?: AbortSignal,
) => {
  return orvalCustomInstance<PropostaHorarioResponseDto[]>(
    { url: `/propostas-horario`, method: "GET", params, signal },
    options,
  )
}

export const getPropostasHorarioControllerFindAllQueryKey = (
  params?: PropostasHorarioControllerFindAllParams,
) => {
  return ["propostas-horario", ...(params ? [params] : [])] as const
}

export const getPropostasHorarioControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof propostasHorarioControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params?: PropostasHorarioControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof propostasHorarioControllerFindAll>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof orvalCustomInstance>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getPropostasHorarioControllerFindAllQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof propostasHorarioControllerFindAll>>
  > = ({ signal }) =>
    propostasHorarioControllerFindAll(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof propostasHorarioControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PropostasHorarioControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof propostasHorarioControllerFindAll>>
>
export type PropostasHorarioControllerFindAllQueryError = ErrorType<unknown>

export function usePropostasHorarioControllerFindAll<
  TData = Awaited<ReturnType<typeof propostasHorarioControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | PropostasHorarioControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof propostasHorarioControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof propostasHorarioControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof propostasHorarioControllerFindAll>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof orvalCustomInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function usePropostasHorarioControllerFindAll<
  TData = Awaited<ReturnType<typeof propostasHorarioControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params?: PropostasHorarioControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof propostasHorarioControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof propostasHorarioControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof propostasHorarioControllerFindAll>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof orvalCustomInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePropostasHorarioControllerFindAll<
  TData = Awaited<ReturnType<typeof propostasHorarioControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params?: PropostasHorarioControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof propostasHorarioControllerFindAll>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof orvalCustomInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Listar todas as propostas
 */

export function usePropostasHorarioControllerFindAll<
  TData = Awaited<ReturnType<typeof propostasHorarioControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params?: PropostasHorarioControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof propostasHorarioControllerFindAll>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof orvalCustomInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getPropostasHorarioControllerFindAllQueryOptions(
    params,
    options,
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Busca a proposta em estado DRAFT ativa para o coordenador autenticado
 * @summary Buscar proposta DRAFT ativa
 */
export const propostasHorarioControllerFindDraftAtiva = (
  params: PropostasHorarioControllerFindDraftAtivaParams,
  options?: SecondParameter<typeof orvalCustomInstance>,
  signal?: AbortSignal,
) => {
  return orvalCustomInstance<PropostaHorarioResponseDto | void>(
    { url: `/propostas-horario/draft-ativa`, method: "GET", params, signal },
    options,
  )
}

export const getPropostasHorarioControllerFindDraftAtivaQueryKey = (
  params: PropostasHorarioControllerFindDraftAtivaParams,
) => {
  return [
    "propostas-horario",
    "draft-ativa",
    ...(params ? [params] : []),
  ] as const
}

export const getPropostasHorarioControllerFindDraftAtivaQueryOptions = <
  TData = Awaited<ReturnType<typeof propostasHorarioControllerFindDraftAtiva>>,
  TError = ErrorType<void>,
>(
  params: PropostasHorarioControllerFindDraftAtivaParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof propostasHorarioControllerFindDraftAtiva>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof orvalCustomInstance>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getPropostasHorarioControllerFindDraftAtivaQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof propostasHorarioControllerFindDraftAtiva>>
  > = ({ signal }) =>
    propostasHorarioControllerFindDraftAtiva(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof propostasHorarioControllerFindDraftAtiva>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PropostasHorarioControllerFindDraftAtivaQueryResult = NonNullable<
  Awaited<ReturnType<typeof propostasHorarioControllerFindDraftAtiva>>
>
export type PropostasHorarioControllerFindDraftAtivaQueryError = ErrorType<void>

export function usePropostasHorarioControllerFindDraftAtiva<
  TData = Awaited<ReturnType<typeof propostasHorarioControllerFindDraftAtiva>>,
  TError = ErrorType<void>,
>(
  params: PropostasHorarioControllerFindDraftAtivaParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof propostasHorarioControllerFindDraftAtiva>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof propostasHorarioControllerFindDraftAtiva>>,
          TError,
          Awaited<ReturnType<typeof propostasHorarioControllerFindDraftAtiva>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof orvalCustomInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function usePropostasHorarioControllerFindDraftAtiva<
  TData = Awaited<ReturnType<typeof propostasHorarioControllerFindDraftAtiva>>,
  TError = ErrorType<void>,
>(
  params: PropostasHorarioControllerFindDraftAtivaParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof propostasHorarioControllerFindDraftAtiva>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof propostasHorarioControllerFindDraftAtiva>>,
          TError,
          Awaited<ReturnType<typeof propostasHorarioControllerFindDraftAtiva>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof orvalCustomInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePropostasHorarioControllerFindDraftAtiva<
  TData = Awaited<ReturnType<typeof propostasHorarioControllerFindDraftAtiva>>,
  TError = ErrorType<void>,
>(
  params: PropostasHorarioControllerFindDraftAtivaParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof propostasHorarioControllerFindDraftAtiva>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof orvalCustomInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Buscar proposta DRAFT ativa
 */

export function usePropostasHorarioControllerFindDraftAtiva<
  TData = Awaited<ReturnType<typeof propostasHorarioControllerFindDraftAtiva>>,
  TError = ErrorType<void>,
>(
  params: PropostasHorarioControllerFindDraftAtivaParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof propostasHorarioControllerFindDraftAtiva>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof orvalCustomInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getPropostasHorarioControllerFindDraftAtivaQueryOptions(
    params,
    options,
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Lista todas as propostas de horário do coordenador autenticado
 * @summary Listar minhas propostas
 */
export const propostasHorarioControllerFindMinhasPropostas = (
  params?: PropostasHorarioControllerFindMinhasPropostasParams,
  options?: SecondParameter<typeof orvalCustomInstance>,
  signal?: AbortSignal,
) => {
  return orvalCustomInstance<PropostaHorarioResponseDto[]>(
    { url: `/propostas-horario/minhas`, method: "GET", params, signal },
    options,
  )
}

export const getPropostasHorarioControllerFindMinhasPropostasQueryKey = (
  params?: PropostasHorarioControllerFindMinhasPropostasParams,
) => {
  return ["propostas-horario", "minhas", ...(params ? [params] : [])] as const
}

export const getPropostasHorarioControllerFindMinhasPropostasQueryOptions = <
  TData = Awaited<
    ReturnType<typeof propostasHorarioControllerFindMinhasPropostas>
  >,
  TError = ErrorType<unknown>,
>(
  params?: PropostasHorarioControllerFindMinhasPropostasParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof propostasHorarioControllerFindMinhasPropostas>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof orvalCustomInstance>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getPropostasHorarioControllerFindMinhasPropostasQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof propostasHorarioControllerFindMinhasPropostas>>
  > = ({ signal }) =>
    propostasHorarioControllerFindMinhasPropostas(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof propostasHorarioControllerFindMinhasPropostas>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PropostasHorarioControllerFindMinhasPropostasQueryResult =
  NonNullable<
    Awaited<ReturnType<typeof propostasHorarioControllerFindMinhasPropostas>>
  >
export type PropostasHorarioControllerFindMinhasPropostasQueryError =
  ErrorType<unknown>

export function usePropostasHorarioControllerFindMinhasPropostas<
  TData = Awaited<
    ReturnType<typeof propostasHorarioControllerFindMinhasPropostas>
  >,
  TError = ErrorType<unknown>,
>(
  params: undefined | PropostasHorarioControllerFindMinhasPropostasParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof propostasHorarioControllerFindMinhasPropostas>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof propostasHorarioControllerFindMinhasPropostas>
          >,
          TError,
          Awaited<
            ReturnType<typeof propostasHorarioControllerFindMinhasPropostas>
          >
        >,
        "initialData"
      >
    request?: SecondParameter<typeof orvalCustomInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function usePropostasHorarioControllerFindMinhasPropostas<
  TData = Awaited<
    ReturnType<typeof propostasHorarioControllerFindMinhasPropostas>
  >,
  TError = ErrorType<unknown>,
>(
  params?: PropostasHorarioControllerFindMinhasPropostasParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof propostasHorarioControllerFindMinhasPropostas>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof propostasHorarioControllerFindMinhasPropostas>
          >,
          TError,
          Awaited<
            ReturnType<typeof propostasHorarioControllerFindMinhasPropostas>
          >
        >,
        "initialData"
      >
    request?: SecondParameter<typeof orvalCustomInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePropostasHorarioControllerFindMinhasPropostas<
  TData = Awaited<
    ReturnType<typeof propostasHorarioControllerFindMinhasPropostas>
  >,
  TError = ErrorType<unknown>,
>(
  params?: PropostasHorarioControllerFindMinhasPropostasParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof propostasHorarioControllerFindMinhasPropostas>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof orvalCustomInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Listar minhas propostas
 */

export function usePropostasHorarioControllerFindMinhasPropostas<
  TData = Awaited<
    ReturnType<typeof propostasHorarioControllerFindMinhasPropostas>
  >,
  TError = ErrorType<unknown>,
>(
  params?: PropostasHorarioControllerFindMinhasPropostasParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof propostasHorarioControllerFindMinhasPropostas>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof orvalCustomInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions =
    getPropostasHorarioControllerFindMinhasPropostasQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Busca uma proposta de horário específica pelo ID
 * @summary Buscar proposta por ID
 */
export const propostasHorarioControllerFindOne = (
  id: string,
  options?: SecondParameter<typeof orvalCustomInstance>,
  signal?: AbortSignal,
) => {
  return orvalCustomInstance<PropostaHorarioResponseDto>(
    { url: `/propostas-horario/${id}`, method: "GET", signal },
    options,
  )
}

export const getPropostasHorarioControllerFindOneQueryKey = (id: string) => {
  return ["propostas-horario", id] as const
}

export const getPropostasHorarioControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof propostasHorarioControllerFindOne>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof propostasHorarioControllerFindOne>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof orvalCustomInstance>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getPropostasHorarioControllerFindOneQueryKey(id)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof propostasHorarioControllerFindOne>>
  > = ({ signal }) =>
    propostasHorarioControllerFindOne(id, requestOptions, signal)

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof propostasHorarioControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PropostasHorarioControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof propostasHorarioControllerFindOne>>
>
export type PropostasHorarioControllerFindOneQueryError = ErrorType<void>

export function usePropostasHorarioControllerFindOne<
  TData = Awaited<ReturnType<typeof propostasHorarioControllerFindOne>>,
  TError = ErrorType<void>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof propostasHorarioControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof propostasHorarioControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof propostasHorarioControllerFindOne>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof orvalCustomInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function usePropostasHorarioControllerFindOne<
  TData = Awaited<ReturnType<typeof propostasHorarioControllerFindOne>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof propostasHorarioControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof propostasHorarioControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof propostasHorarioControllerFindOne>>
        >,
        "initialData"
      >
    request?: SecondParameter<typeof orvalCustomInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePropostasHorarioControllerFindOne<
  TData = Awaited<ReturnType<typeof propostasHorarioControllerFindOne>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof propostasHorarioControllerFindOne>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof orvalCustomInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Buscar proposta por ID
 */

export function usePropostasHorarioControllerFindOne<
  TData = Awaited<ReturnType<typeof propostasHorarioControllerFindOne>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof propostasHorarioControllerFindOne>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof orvalCustomInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getPropostasHorarioControllerFindOneQueryOptions(
    id,
    options,
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Envia uma proposta em estado DRAFT para aprovação (muda status para PENDENTE_APROVACAO)
 * @summary Enviar proposta para aprovação
 */
export const propostasHorarioControllerEnviar = (
  id: string,
  options?: SecondParameter<typeof orvalCustomInstance>,
  signal?: AbortSignal,
) => {
  return orvalCustomInstance<PropostaHorarioResponseDto>(
    { url: `/propostas-horario/${id}/enviar`, method: "POST", signal },
    options,
  )
}

export const getPropostasHorarioControllerEnviarMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof propostasHorarioControllerEnviar>>,
    TError,
    { id: string },
    TContext
  >
  request?: SecondParameter<typeof orvalCustomInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof propostasHorarioControllerEnviar>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["propostasHorarioControllerEnviar"]
  const { mutation: mutationOptions, request: requestOptions } =
    options ?
      (
        options.mutation &&
        "mutationKey" in options.mutation &&
        options.mutation.mutationKey
      ) ?
        options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof propostasHorarioControllerEnviar>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return propostasHorarioControllerEnviar(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PropostasHorarioControllerEnviarMutationResult = NonNullable<
  Awaited<ReturnType<typeof propostasHorarioControllerEnviar>>
>

export type PropostasHorarioControllerEnviarMutationError = ErrorType<void>

/**
 * @summary Enviar proposta para aprovação
 */
export const usePropostasHorarioControllerEnviar = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof propostasHorarioControllerEnviar>>,
      TError,
      { id: string },
      TContext
    >
    request?: SecondParameter<typeof orvalCustomInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof propostasHorarioControllerEnviar>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions =
    getPropostasHorarioControllerEnviarMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Aprova uma proposta em estado PENDENTE_APROVACAO (muda status para APROVADA)
 * @summary Aprovar proposta
 */
export const propostasHorarioControllerAprovar = (
  id: string,
  aprovarPropostaDto: BodyType<AprovarPropostaDto>,
  options?: SecondParameter<typeof orvalCustomInstance>,
  signal?: AbortSignal,
) => {
  return orvalCustomInstance<PropostaHorarioResponseDto>(
    {
      url: `/propostas-horario/${id}/aprovar`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: aprovarPropostaDto,
      signal,
    },
    options,
  )
}

export const getPropostasHorarioControllerAprovarMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof propostasHorarioControllerAprovar>>,
    TError,
    { id: string; data: BodyType<AprovarPropostaDto> },
    TContext
  >
  request?: SecondParameter<typeof orvalCustomInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof propostasHorarioControllerAprovar>>,
  TError,
  { id: string; data: BodyType<AprovarPropostaDto> },
  TContext
> => {
  const mutationKey = ["propostasHorarioControllerAprovar"]
  const { mutation: mutationOptions, request: requestOptions } =
    options ?
      (
        options.mutation &&
        "mutationKey" in options.mutation &&
        options.mutation.mutationKey
      ) ?
        options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof propostasHorarioControllerAprovar>>,
    { id: string; data: BodyType<AprovarPropostaDto> }
  > = (props) => {
    const { id, data } = props ?? {}

    return propostasHorarioControllerAprovar(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PropostasHorarioControllerAprovarMutationResult = NonNullable<
  Awaited<ReturnType<typeof propostasHorarioControllerAprovar>>
>
export type PropostasHorarioControllerAprovarMutationBody =
  BodyType<AprovarPropostaDto>
export type PropostasHorarioControllerAprovarMutationError = ErrorType<void>

/**
 * @summary Aprovar proposta
 */
export const usePropostasHorarioControllerAprovar = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof propostasHorarioControllerAprovar>>,
      TError,
      { id: string; data: BodyType<AprovarPropostaDto> },
      TContext
    >
    request?: SecondParameter<typeof orvalCustomInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof propostasHorarioControllerAprovar>>,
  TError,
  { id: string; data: BodyType<AprovarPropostaDto> },
  TContext
> => {
  const mutationOptions =
    getPropostasHorarioControllerAprovarMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Rejeita uma proposta em estado PENDENTE_APROVACAO (muda status para REJEITADA)
 * @summary Rejeitar proposta
 */
export const propostasHorarioControllerRejeitar = (
  id: string,
  rejeitarPropostaDto: BodyType<RejeitarPropostaDto>,
  options?: SecondParameter<typeof orvalCustomInstance>,
  signal?: AbortSignal,
) => {
  return orvalCustomInstance<PropostaHorarioResponseDto>(
    {
      url: `/propostas-horario/${id}/rejeitar`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: rejeitarPropostaDto,
      signal,
    },
    options,
  )
}

export const getPropostasHorarioControllerRejeitarMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof propostasHorarioControllerRejeitar>>,
    TError,
    { id: string; data: BodyType<RejeitarPropostaDto> },
    TContext
  >
  request?: SecondParameter<typeof orvalCustomInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof propostasHorarioControllerRejeitar>>,
  TError,
  { id: string; data: BodyType<RejeitarPropostaDto> },
  TContext
> => {
  const mutationKey = ["propostasHorarioControllerRejeitar"]
  const { mutation: mutationOptions, request: requestOptions } =
    options ?
      (
        options.mutation &&
        "mutationKey" in options.mutation &&
        options.mutation.mutationKey
      ) ?
        options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof propostasHorarioControllerRejeitar>>,
    { id: string; data: BodyType<RejeitarPropostaDto> }
  > = (props) => {
    const { id, data } = props ?? {}

    return propostasHorarioControllerRejeitar(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PropostasHorarioControllerRejeitarMutationResult = NonNullable<
  Awaited<ReturnType<typeof propostasHorarioControllerRejeitar>>
>
export type PropostasHorarioControllerRejeitarMutationBody =
  BodyType<RejeitarPropostaDto>
export type PropostasHorarioControllerRejeitarMutationError = ErrorType<void>

/**
 * @summary Rejeitar proposta
 */
export const usePropostasHorarioControllerRejeitar = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof propostasHorarioControllerRejeitar>>,
      TError,
      { id: string; data: BodyType<RejeitarPropostaDto> },
      TContext
    >
    request?: SecondParameter<typeof orvalCustomInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof propostasHorarioControllerRejeitar>>,
  TError,
  { id: string; data: BodyType<RejeitarPropostaDto> },
  TContext
> => {
  const mutationOptions =
    getPropostasHorarioControllerRejeitarMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
