// =============================================================================
// PROPOSTAS HORÁRIO FEATURE EXPORTS
// =============================================================================
// Barrel file centralizado - todos os imports são diretos dos arquivos específicos

// -----------------------------------------------------------------------------
// Types & Interfaces
// -----------------------------------------------------------------------------
export * from "./types/proposta-types"
export type {
  PropostaStatus,
  PropostaListItem,
  PropostaDetails,
  PropostaFilters,
  PropostaSortOptions,
  CreatePropostaData,
  SubmitPropostaData,
  ApprovePropostaData,
  RejectPropostaData,
  PropostaPermissions,
  PropostaUIState,
  PropostaActionMenuProps,
  PropostaStatusBadgeProps,
} from "./types/proposta-types"

// Status configuration
export { PROPOSTA_STATUS_CONFIG } from "./types/proposta-types"

// -----------------------------------------------------------------------------
// Validation Schemas
// -----------------------------------------------------------------------------
export * from "./schemas/proposta-schemas"
export {
  createPropostaFormSchema,
  updatePropostaFormSchema,
  submitPropostaFormSchema,
  approvePropostaFormSchema,
  rejectPropostaFormSchema,
  reopenPropostaFormSchema,
  propostaFiltersSchema,
  propostaSortSchema,
  propostaSearchSchema,
  propostaListFiltersSchema,
  cursoSelectSchema,
  periodoLetivoSelectSchema,
  validationUtils,
  validationMessages,
} from "./schemas/proposta-schemas"

// Schema types
export type {
  CreatePropostaFormData,
  UpdatePropostaFormData,
  SubmitPropostaFormData,
  ApprovePropostaFormData,
  RejectPropostaFormData,
  ReopenPropostaFormData,
  PropostaFiltersFormData,
  PropostaSortFormData,
  PropostaSearchFormData,
  PropostaListFiltersFormData,
  CursoSelectData,
  PeriodoLetivoSelectData,
} from "./schemas/proposta-schemas"

// -----------------------------------------------------------------------------
// React Query Hooks (Generated by Orval)
// -----------------------------------------------------------------------------
export {
  usePropostasHorarioControllerFindAll,
  usePropostasHorarioControllerFindOne,
  usePropostasHorarioControllerCreate,
  usePropostasHorarioControllerUpdate,
  usePropostasHorarioControllerSubmit,
  usePropostasHorarioControllerApprove,
  usePropostasHorarioControllerReject,
  usePropostasHorarioControllerReopen,
  usePropostasHorarioControllerRemove,
} from "@/api-generated/client/propostas-horario/propostas-horario"

// -----------------------------------------------------------------------------
// Custom Hooks (imports diretos)
// -----------------------------------------------------------------------------
export * from "./hooks/use-propostas-horario"
export * from "./hooks/use-schedule-allocation"

// Future custom hooks will be exported here:
// export * from "./hooks/use-proposta-filters"
// export * from "./hooks/use-proposta-permissions"
// export * from "./hooks/use-proposta-status"

// -----------------------------------------------------------------------------
// Components - Schedule/Allocation (imports diretos)
// -----------------------------------------------------------------------------
export * from "./components/alocacao-turmas-horarios/schedule-grid"
export * from "./components/alocacao-turmas-horarios/schedule-cell-container"
export * from "./components/alocacao-turmas-horarios/schedule-cell-view"
export * from "./components/alocacao-turmas-horarios/schedule-allocation-dialog"
export * from "./components/alocacao-turmas-horarios/schedule-grid-types"
export * from "./components/alocacao-turmas-horarios/turno-section"

// -----------------------------------------------------------------------------
// Components - Data Table
// -----------------------------------------------------------------------------
export {
  propostasCoordinatorColumns,
  propostasDirectorColumns,
} from "./components/data-table/propostas-columns"
export { PropostasActionDropdown } from "./components/data-table/propostas-action-dropdown"
export { PropostasFilters } from "./components/data-table/propostas-filters"
export { DiretorPropostasFilters } from "./components/data-table/diretor-propostas-filters"
// Future data table components will be exported here:
// export * from "./components/data-table/propostas-data-table"

// -----------------------------------------------------------------------------
// Components - Dialogs & Forms (futuros componentes)
// -----------------------------------------------------------------------------
// Future dialog components will be exported here:
// export * from "./components/create-proposta-dialog"
// export * from "./components/submit-proposta-dialog"
// export * from "./components/approve-reject-dialogs"

// -----------------------------------------------------------------------------
// Components - UI Elements
// -----------------------------------------------------------------------------
export { PropostaStatusBadge } from "./components/proposta-status-badge"
// Future UI components will be exported here:
// export * from "./components/proposta-schedule-grid"

// -----------------------------------------------------------------------------
// Pages (imports diretos)
// -----------------------------------------------------------------------------
export { PropostasHorarioPage } from "./pages/propostas-horario-page"
export { PropostasListPage } from "./pages/propostas-list-page"
export { CreatePropostaPage } from "./pages/create-proposta-page"
export { PropostaDetailsPage } from "./pages/proposta-details-page"
export { DiretorPropostasListPage } from "./pages/diretor-propostas-list-page"
export { DiretorPropostaDetailsPage } from "./pages/diretor-proposta-details-page"

// -----------------------------------------------------------------------------
// Re-exports from API Generated Code
// -----------------------------------------------------------------------------
export type {
  PropostaHorarioResponseDto,
  PropostaHorarioResponseDtoStatus,
  CoordenadorPropostaDto,
  CursoPropostaDto,
  PeriodoLetivoPropostaDto,
  CreatePropostaHorarioDto,
  UpdatePropostaHorarioDto,
  SubmitPropostaHorarioDto,
  ApprovePropostaDto,
  RejectPropostaDto,
} from "@/api-generated/model"

// -----------------------------------------------------------------------------
// Barrel Export Benefits
// -----------------------------------------------------------------------------
// ✅ Consistência total - apenas um arquivo para gerenciar
// ✅ Imports diretos - sem cascata de re-exports
// ✅ Controle centralizado - fácil manutenção
// ✅ Performance otimizada - tree-shaking eficiente
// ✅ Clareza - tudo explícito em um local

// Usage examples:
// import { PropostaStatus, createPropostaFormSchema, usePropostasHorarioControllerFindAll } from "@/features/propostas-horario"
// import { PropostasListPage, ScheduleGrid } from "@/features/propostas-horario"
