/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


/**
 * Realiza o login do usuário com e-mail e senha.
 * @summary Autentica um usuário e retorna um token JWT
 */
export const authControllerSignInBody = zod.object({
  "email": zod.string().describe('Endereço de e-mail do usuário para login'),
  "senha": zod.string().describe('Senha do usuário (mínimo de 8 caracteres)')
})

export const authControllerSignInResponse = zod.object({
  "accessToken": zod.string().describe('Token de acesso JWT'),
  "usuario": zod.object({
  "id": zod.string().describe('ID único do usuário'),
  "nome": zod.string().describe('Nome completo do usuário'),
  "email": zod.string().describe('Endereço de e-mail do usuário'),
  "papel": zod.enum(['ADMIN', 'DIRETOR', 'COORDENADOR', 'PROFESSOR']).describe('Papel do usuário no sistema'),
  "dataCriacao": zod.string().datetime({}).describe('Data de criação do usuário'),
  "dataAtualizacao": zod.string().datetime({}).describe('Data da última atualização do usuário')
}).describe('Dados do usuário autenticado')
})

/**
 * Cria uma nova conta de usuário. O usuário criado não é logado automaticamente.
 * @summary Registra um novo usuário no sistema
 */
export const authControllerSignUpBodySenhaMin = 8;


export const authControllerSignUpBody = zod.object({
  "nome": zod.string().describe('Nome completo do usuário'),
  "email": zod.string().describe('Endereço de e-mail do usuário (será usado para login)'),
  "senha": zod.string().min(authControllerSignUpBodySenhaMin).describe('Senha do usuário (mínimo de 8 caracteres)'),
  "papel": zod.enum(['ADMIN', 'DIRETOR', 'COORDENADOR', 'PROFESSOR']).describe('Papel do usuário no sistema')
})

