/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Horários Acadêmicos
 * Documentação da API para o Sistema de Elaboração de Horário e Atribuição de Disciplinas
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Cria um novo período letivo
 */
export const periodosLetivosControllerCreateBodyAnoMin = 2000;

export const periodosLetivosControllerCreateBodyAnoMax = 2100;
export const periodosLetivosControllerCreateBodySemestreMax = 2;
export const periodosLetivosControllerCreateBodyStatusDefault = "INATIVO";

export const periodosLetivosControllerCreateBody = zod.object({
  "ano": zod.number().min(periodosLetivosControllerCreateBodyAnoMin).max(periodosLetivosControllerCreateBodyAnoMax).describe('Ano do período letivo'),
  "semestre": zod.number().min(1).max(periodosLetivosControllerCreateBodySemestreMax).describe('Semestre do período letivo (1 ou 2)'),
  "status": zod.enum(['ATIVO', 'INATIVO']).default(periodosLetivosControllerCreateBodyStatusDefault).describe('Status inicial do período letivo'),
  "dataInicio": zod.string().describe('Data de início do período letivo no formato YYYY-MM-DD'),
  "dataFim": zod.string().describe('Data de fim do período letivo no formato YYYY-MM-DD')
})

/**
 * @summary Lista todos os períodos letivos com filtros opcionais
 */
export const periodosLetivosControllerFindAllQueryParams = zod.object({
  "id": zod.string().optional().describe('ID do período letivo'),
  "ano": zod.number().optional().describe('Filtrar por ano'),
  "semestre": zod.number().optional().describe('Filtrar por semestre (1 ou 2)'),
  "status": zod.enum(['ATIVO', 'INATIVO']).optional().describe('Filtrar por status'),
  "dataInicioGte": zod.string().optional().describe('Data de início do período letivo (filtro a partir de)'),
  "dataInicioLte": zod.string().optional().describe('Data de início do período letivo (filtro até)'),
  "dataFimGte": zod.string().optional().describe('Data de fim do período letivo (filtro a partir de)'),
  "dataFimLte": zod.string().optional().describe('Data de fim do período letivo (filtro até)')
})

export const periodosLetivosControllerFindAllResponseItem = zod.object({
  "id": zod.string().describe('ID único do período letivo'),
  "ano": zod.number().describe('Ano do período letivo'),
  "semestre": zod.number().describe('Semestre do período letivo (1 ou 2)'),
  "status": zod.enum(['ATIVO', 'INATIVO']).describe('Status atual do período letivo'),
  "dataInicio": zod.string().describe('Data de início do período letivo'),
  "dataFim": zod.string().describe('Data de fim do período letivo'),
  "dataCriacao": zod.string().describe('Data de criação do registro'),
  "dataAtualizacao": zod.string().describe('Data da última atualização do registro')
})
export const periodosLetivosControllerFindAllResponse = zod.array(periodosLetivosControllerFindAllResponseItem)

/**
 * @summary Busca o período letivo ativo atual
 */
export const periodosLetivosControllerFindPeriodoAtivoResponse = zod.object({
  "id": zod.string().describe('ID único do período letivo'),
  "ano": zod.number().describe('Ano do período letivo'),
  "semestre": zod.number().describe('Semestre do período letivo (1 ou 2)'),
  "status": zod.enum(['ATIVO', 'INATIVO']).describe('Status atual do período letivo'),
  "dataInicio": zod.string().describe('Data de início do período letivo'),
  "dataFim": zod.string().describe('Data de fim do período letivo'),
  "dataCriacao": zod.string().describe('Data de criação do registro'),
  "dataAtualizacao": zod.string().describe('Data da última atualização do registro')
})

/**
 * @summary Busca um período letivo pelo ID
 */
export const periodosLetivosControllerFindOneParams = zod.object({
  "id": zod.string().describe('ID do período letivo (UUID)')
})

export const periodosLetivosControllerFindOneResponse = zod.object({
  "id": zod.string().describe('ID único do período letivo'),
  "ano": zod.number().describe('Ano do período letivo'),
  "semestre": zod.number().describe('Semestre do período letivo (1 ou 2)'),
  "status": zod.enum(['ATIVO', 'INATIVO']).describe('Status atual do período letivo'),
  "dataInicio": zod.string().describe('Data de início do período letivo'),
  "dataFim": zod.string().describe('Data de fim do período letivo'),
  "dataCriacao": zod.string().describe('Data de criação do registro'),
  "dataAtualizacao": zod.string().describe('Data da última atualização do registro')
})

/**
 * @summary Atualiza um período letivo existente
 */
export const periodosLetivosControllerUpdateParams = zod.object({
  "id": zod.string().describe('ID do período letivo a ser atualizado (UUID)')
})

export const periodosLetivosControllerUpdateBodyAnoMin = 2000;

export const periodosLetivosControllerUpdateBodyAnoMax = 2100;
export const periodosLetivosControllerUpdateBodySemestreMax = 2;
export const periodosLetivosControllerUpdateBodyStatusDefault = "INATIVO";

export const periodosLetivosControllerUpdateBody = zod.object({
  "ano": zod.number().min(periodosLetivosControllerUpdateBodyAnoMin).max(periodosLetivosControllerUpdateBodyAnoMax).optional().describe('Ano do período letivo'),
  "semestre": zod.number().min(1).max(periodosLetivosControllerUpdateBodySemestreMax).optional().describe('Semestre do período letivo (1 ou 2)'),
  "status": zod.enum(['ATIVO', 'INATIVO']).default(periodosLetivosControllerUpdateBodyStatusDefault).describe('Status inicial do período letivo'),
  "dataInicio": zod.string().optional().describe('Data de início do período letivo no formato YYYY-MM-DD'),
  "dataFim": zod.string().optional().describe('Data de fim do período letivo no formato YYYY-MM-DD')
})

export const periodosLetivosControllerUpdateResponse = zod.object({
  "id": zod.string().describe('ID único do período letivo'),
  "ano": zod.number().describe('Ano do período letivo'),
  "semestre": zod.number().describe('Semestre do período letivo (1 ou 2)'),
  "status": zod.enum(['ATIVO', 'INATIVO']).describe('Status atual do período letivo'),
  "dataInicio": zod.string().describe('Data de início do período letivo'),
  "dataFim": zod.string().describe('Data de fim do período letivo'),
  "dataCriacao": zod.string().describe('Data de criação do registro'),
  "dataAtualizacao": zod.string().describe('Data da última atualização do registro')
})

/**
 * @summary Remove um período letivo
 */
export const periodosLetivosControllerRemoveParams = zod.object({
  "id": zod.string().describe('ID do período letivo a ser removido (UUID)')
})

export const periodosLetivosControllerRemoveResponse = zod.object({
  "id": zod.string().describe('ID único do período letivo'),
  "ano": zod.number().describe('Ano do período letivo'),
  "semestre": zod.number().describe('Semestre do período letivo (1 ou 2)'),
  "status": zod.enum(['ATIVO', 'INATIVO']).describe('Status atual do período letivo'),
  "dataInicio": zod.string().describe('Data de início do período letivo'),
  "dataFim": zod.string().describe('Data de fim do período letivo'),
  "dataCriacao": zod.string().describe('Data de criação do registro'),
  "dataAtualizacao": zod.string().describe('Data da última atualização do registro')
})

/**
 * @summary Altera o status de um período letivo
 */
export const periodosLetivosControllerChangeStatusParams = zod.object({
  "id": zod.string().describe('ID do período letivo (UUID)')
})

export const periodosLetivosControllerChangeStatusBody = zod.object({
  "status": zod.enum(['ATIVO', 'INATIVO']).describe('Novo status do período letivo')
})

export const periodosLetivosControllerChangeStatusResponse = zod.object({
  "id": zod.string().describe('ID único do período letivo'),
  "ano": zod.number().describe('Ano do período letivo'),
  "semestre": zod.number().describe('Semestre do período letivo (1 ou 2)'),
  "status": zod.enum(['ATIVO', 'INATIVO']).describe('Status atual do período letivo'),
  "dataInicio": zod.string().describe('Data de início do período letivo'),
  "dataFim": zod.string().describe('Data de fim do período letivo'),
  "dataCriacao": zod.string().describe('Data de criação do registro'),
  "dataAtualizacao": zod.string().describe('Data da última atualização do registro')
})

