export { PropostasHorarioPage } from "./propostas-horario-page"
export { PropostasListPage } from "./propostas-list-page"
export { CreatePropostaPage } from "./create-proposta-page"
export { PropostaDetailsPage } from "./proposta-details-page"
export { DiretorPropostasListPage } from "./diretor-propostas-list-page"
export { DiretorPropostaDetailsPage } from "./diretor-proposta-details-page"
